### ISSUE TITLE
TargetSecretSyncFailed: "secret data is empty" but is not

### ISSUE THREAD

**Issue by simonostendorf** [syself/cluster-api-provider-hetzner#1007]
/kind bug

**What steps did you take and what happened:**

I am getting an `TargetSecretSyncFailed` error while creating a cluster. The first controlplane and the machinedeployment gets spawned correctly but other controlplane nodes will not come up. 

Error message `TargetSecretSyncFailed`:
```
failed to reconcile target secret: failed to create secret: Secret "hcloud-token" is invalid: data[]: Invalid value: "": a valid config key must consist of alphanumeric characters, ''-'', ''_'' or ''.'' (e.g. ''key.name'',  or ''KEY_NAME'',  or ''key-name'', regex used for validation is ''[-._a-zA-Z0-9]+'')
```

Dont know why I am getting the error because the data.token field is not empty like you can see in the yaml dump here:

Secret Content:
```
apiVersion: v1
kind: Secret
type: Opaque
data:
  token: <BASE64_TOKEN_HERE>
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"clusterctl.cluster.x-k8s.io/move":""},"name":"hcloud-token","namespace":"default"},"stringData":{"token":"<PLAINTEXT_TOKEN_HERE>"}}
  creationTimestamp: "2023-10-03T09:00:27Z"
  finalizers:
  - hetznercluster.infrastructure.cluster.x-k8s.io/secret
  labels:
    caph.environment: owned
    clusterctl.cluster.x-k8s.io/move: ""
  name: hcloud-token
  namespace: default
  ownerReferences:
  - apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: HetznerCluster
    name: test-v4t28
    uid: 0957eafb-c9ec-4be2-b307-b3e8387e35c7
  resourceVersion: "1705980"
  uid: f0314d9d-8112-4807-a566-817669fcafde
```

**What did you expect to happen:**
I expect the secret to be created sucessfully in the downstream cluster because it is a valid secret in the mgmt cluster.

**Anything else you would like to add:**
(nothing)

**Environment:**

- cluster-api-provider-hetzner version: v1.0.0-beta.25
- cluster-api version: v1.5.2
- Kubernetes version: v1.27.3

**Comment by simonostendorf** [comment]
Further tests show the following finding: 
If I set something in the `HetznerClusterTemplate` for `spec.hetznerSecretRef.key.hetznerRobotPassword` and `spec.hetznerSecretRef.key.hetznerRobotUser` and also specify these values in the Secret, everything works without problems. I think it is a problem when creating the `HetznerCluster` from the `HetznerClusterTemplate`, because `spec.hetznerSecretRef.key.hetznerRobotPassword` and `spec.hetznerSecretRef.key.hetznerRobotUser` are set to empty strings if they are not previously defined in the template. Is this a bug in CAPH or a general CAPI bug?

**Comment by janiskemper** [comment]
Mmh we populate a secret and store it in the workload clusters. That's called "target secret". In there, we also store the Hetzner credentials. 

Maybe, we have not thought of the case that the key is not specified (https://github.com/syself/cluster-api-provider-hetzner/blob/main/controllers/hetznercluster_controller.go#L502)

So if `hetznerSecretRef.key.hetznerRobotUser` and `hetznerSecretRef.key.hetznerRobotPassword` are not both specified, we should actually get this error that you got there. My only question is why this has not occurred before though. Seems like nobody has tried to use it without any Hetzner Dedicated configuration

**Comment by simonostendorf** [comment]
When using only HetznerCluster without the Topology feature I can leave `spec.hetznerSecretRef.key.hetznerRobotUser` and `spec.hetznerSecretRef.key.hetznerRobotPassword` empty and it is working. 

Could the creation from the template be adjusted so that the empty values are also empty (maybe set "omitEmpty" in the api spec?)

**Comment by janiskemper** [comment]
a workaround for you is to use empty values btw! Do you wanna try that out? Maybe some API change like you proposed would help. 

Otherwise, I suppose that an if else statement in the code to check whether the key is empty / an empty string should still work

**Comment by simonostendorf** [comment]
> a workaround for you is to use empty values btw! Do you wanna try that out? Maybe some API change like you proposed would help.
> 
> Otherwise, I suppose that an if else statement in the code to check whether the key is empty / an empty string should still work

I used dummy values (just "username" and "password") and these are working. Empty string was the default inside the HetznerCluster that was created from the Template (I think because of the missing `omitEmpty`) so they are not working.

**Comment by batistein** [comment]
Typically, we assign an empty string as the value in the secret. However, there's certainly room for enhancement in the CRDs.

**Comment by simonostendorf** [comment]
> Typically, we assign an empty string as the value in the secret. However, there's certainly room for enhancement in the CRDs.

Usind an empty string in the secret and a valid reference inside the HetznerClusterTemplate works. However I think the crd could be approved to prevent these errors. :)

**Comment by batistein** [comment]
@simonostendorf, my apologies for the oversight. Upon rechecking, I realized the issue arises only when using the provided clusterclass template. My previous method, as mentioned, is often a shortcut to avoid modifications in the custom resource. It's easy to inadvertently leave some values empty during the secret setup.

To clarify:
1. There's no bug in the CRDs; they function as expected, and you can indeed leave keys empty.
1. The current clusterclass template doesn't support this. However, since the templates provided in the release are primarily for testing, you can adjust the clusterclass by removing the relevant lines to suit your specific needs.

**Comment by janiskemper** [comment]
@batistein and me talked about this again. We will update the code so that we don't try to add a key value pair with an empty key anymore. 

I am personally not aware of the details of the existing templates/custom resources and potential workarounds, but that's what I can propose.
