### ISSUE TITLE
Use of new package repositories

### ISSUE THREAD

**Issue by berendt** [syself/cluster-api-provider-hetzner#1013]
/kind bug

Because of the use of the old K8s package repositories (apt.kubernetes.io) at the moment it is not possible to use newer Kubernetes versions. We tested with 1.25.15:

```
Reading package lists...
Building dependency tree...
Reading state information...
Package kubeadm is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package kubelet is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package kubectl is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Version '1.25.15-00' for 'kubelet' was not found
E: Version '1.25.15-00' for 'kubeadm' was not found
E: Version '1.25.15-00' for 'kubectl' was not found
```

Further details: https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/

Can you please switch to the new repositories?

**Comment by kranurag7** [comment]
@berendt We released a new version yesterday where we switched to the `pkgs.k8s.io` for fetching packages.
https://github.com/syself/cluster-api-provider-hetzner/releases/tag/v1.0.0-beta.27 

This release should fix the issue described above. Please let us know if something doesn't work for you.

**Comment by berendt** [comment]
I'll hand it over and have it tested on our site.
