### ISSUE TITLE
Fix usage of webhooks in unit tests with envtest

### ISSUE THREAD

**Issue by janiskemper** [syself/cluster-api-provider-hetzner#105]
/kind bug

**What steps did you take and what happened:**
I tried to include unit tests in the ```/controllers``` folder that test the functionality of webhooks. However, as far as I can see, no webhooks are used at any stage and therefore the validation of webhooks does not work at all in our current unit tests. I don't know why, as the webhook port should be set correctly. 

I tried to disable the renaming happening in the function ```appendWebhookConfiguration```, but it didn't change anything.

**What did you expect to happen:**
Webhook server should be started in ```NewTestEnvironment``` (which is the case currently, as we check this in ```WaitForWebhooks```) and the webhooks should be triggered when a relevant object is created or updated.

**Environment:**
- cluster-api-provider-hetzner version: v1.0.0-alpha.10
- Kubernetes version: 1.22
- OS: Fedora 34

**Comment by batistein** [comment]
@janiskemper what is the current status?

**Comment by apricote** [comment]
If it is fine by you, I would like to take a look at this.

**Comment by batistein** [comment]
@apricote this would be awesome! If you need further informations we can schedule a call ;)

**Comment by apricote** [comment]
At some point since this issue was created, the webhooks seem to have started working in the envtest. If I apply following diff, that causes the `HcloudMachine` validate webhook to always fail, the unit tests also start to fail with the error message:

```patch
diff --git a/api/v1beta1/hcloudmachine_webhook.go b/api/v1beta1/hcloudmachine_webhook.go
index e7dfd4c..c2d6554 100644
--- a/api/v1beta1/hcloudmachine_webhook.go
+++ b/api/v1beta1/hcloudmachine_webhook.go
@@ -66,9 +66,8 @@ var _ webhook.Validator = &HCloudMachine{}
 // ValidateCreate implements webhook.Validator so a webhook will be registered for the type.
 func (r *HCloudMachine) ValidateCreate() error {
 	hcloudmachinelog.V(1).Info("validate create", "name", r.Name)
-	var allErrs field.ErrorList
 
-	return aggregateObjErrors(r.GroupVersionKind().GroupKind(), r.Name, allErrs)
+	return fmt.Errorf("HCloudMachine.ValidateCreate failed")
 }
 
 // ValidateUpdate implements webhook.Validator so a webhook will be registered for the type.
```

@batistein If you know of a specific webhook that is not working as expected, I can take a look at that.

---

While debugging this, I found that logs coming from the HcloudMachine webhooks were not included in the ginkgo log output after a failed test. This happens because the logger is configured with `utils.GetDefaultLogger("info")`, which causes `V(0)` and lower to be logged, but the actual logging statements were using `V(1)`.

**Comment by apricote** [comment]
Actually it looks like the webhooks for `HetznerBareMetalRemediation` and `HetznerBareMetalRemediationTemplate` were not started. Adding them now.

**Comment by janiskemper** [comment]
In `envtest.go` we define the logger for the testing environment. You could maybe try to configure it with debug logging. I think that should be the reason.

Thanks for adding them, if they were indeed not started. I suppose that we don't have tests for them though. 

You can close this issue if you think everything is working! Thanks a lot for looking into this!

**Comment by batistein** [comment]
Is this fixed? @janiskemper @apricote

**Comment by apricote** [comment]
All webhooks are running in envtest since #552.

The issue can be closed from my side (but I don't have permissions for that).
