### ISSUE TITLE
HCloud Snapshot Support

### ISSUE THREAD

**Issue by benedikt-bartscher** [syself/cluster-api-provider-hetzner#1056]
/kind feature

**Describe the solution you'd like**
A new CRD called something like "HCloudSnapshotPolicy" which describes intervals for automatic hcloud snapshot creation and deletion for specific Machines filtered by labels.

**Comment by janiskemper** [comment]
can you please describe your use case?

**Comment by Preisschild** [comment]
HCloud doesn't offer snapshots for its volumes.
