### ISSUE TITLE
Provisioning of UEFI machines not possible

### ISSUE THREAD

**Issue by KoffeinKaio** [syself/cluster-api-provider-hetzner#1118]
/kind bug

**What steps did you take and what happened:**
When provisioning a hetzner bare meta host with UEFI enabled, the host ist stuck in "image-installing"

The installimage.sh in the rescue errors out because the LINE
PART /boot/efi esp 265M (or something like that)
is missing. 
Also the provisioner would have to make sure the device with roothint is booted.

ERROR: ESP missing or multiple ESP found

**What did you expect to happen:**
I expect this to be added automatically on detecting an efi-enabled system

**Anything else you would like to add:**

Line in autoconfig 'PART /boot/efi esp 265M' is enough.
Also the provisioner would have to make sure the device with roothint is booted
It should be possible to also add this in HetznerBareMetalMachineTemplate, but its a hassle to work with labels to support legacy **and** UEFI

**Environment:**

- cluster-api-provider-hetzner version: v1.0.0-beta.27
- Kubernetes version: v1.28.4
- OS (e.g. from `/etc/os-release`): Debian GNU/Linux 12 (bookworm) Rescue

**Comment by kranurag7** [comment]
Hey @KoffeinKaio 
Hetzner UEFI Boot as of now is in beta and not supported by the project at the moment. 
Ref: https://docs.hetzner.com/robot/dedicated-server/operating-systems/uefi/#introduction
To solve the issue please contact Hetzner support, so that they change the machine to legacy boot.

**Comment by KoffeinKaio** [comment]
As it seems (at least as our server guy said) newer Server Versions, for example AX52 only support UEFI.

> With all new dedicated root server models, Hetzner Online will support UEFI boot natively and discontinue legacy boot (CSM) support. 


Ill try to contact hetzner to get a clarification

**Comment by KoffeinKaio** [comment]
> Ill try to contact hetzner to get a clarification

Answer of hetzner:
"wir bedauern, aber dies ist bei den gemieteten AX52 und auch anderen Servermodellen bereits nicht mehr möglich. Die Server sind UEFI "only" und bieten hier keine Änderungsmöglichkeit."

English:
"We regret to inform you that this is no longer possible with the rented AX52 and other server models. The servers are UEFI 'only' and do not offer any option to change this."

**Comment by guettli** [comment]
I confirm that the merged PR makes it possible to run the Syself capi provider on Hetzner bare-metal servers with UEFI.

If the provisioning fails to enter the rescue system to install the node image, then the boot order could be wrong.

Then the old OS on the disk gets booted and not the rescue system.

In this case either contact the Hetzner support, or use `efibootmgr` if you have access to the machine via ssh.

**Comment by guettli** [comment]
@KoffeinKaio [beta32](https://github.com/syself/cluster-api-provider-hetzner/releases/tag/v1.0.0-beta.32) was released and we sucessfully provisioned some uefi machines (with mdraid and without). Please try it, and provide feedback if it worked for you.
