### ISSUE TITLE
Better structure of CapH docs

### ISSUE THREAD

**Issue by Sayanta66** [syself/cluster-api-provider-hetzner#1124]
This issue indicates a better structure of the CapH docs in terms of indexing. The following ideas can be seen below:

**Comment by Sayanta66** [comment]
A rough idea of the structure:

- Preparation doc should be in the Quickstart section
- After preparation, the getting started doc should be there.
- The ClusterAPI quickstart link shouldn't be in the quickstart section as a separate entity but be in somewhere in the getting started doc and that too in the prerequisite area.

**Comment by Sayanta66** [comment]
@janiskemper Do you think this will be better?

**Comment by janiskemper** [comment]
sounds good!

**Comment by Sayanta66** [comment]
Reference links - https://cluster-api.sigs.k8s.io/reference/api_reference
https://doc.crds.dev/github.com/syself/cluster-api-provider-hetzner
https://cluster-api.sigs.k8s.io/developer/guide

**Comment by Sayanta66** [comment]
1. Introduction
2. Preparation
3. Quickstart
4. Personas (This section looks good on the CAPI docs but not sure whether will be a right fit for the CAPH docs)

**Comment by Sayanta66** [comment]
In the CSO repository, we have some docs about baremetal. For example, the [Provisioning Phases](https://github.com/syself/cluster-stack-operator/blob/main/docs/book/src/provider-hetzner-baremetal.md#provisioning-phases) are documented there. I think docs about the phases should be in caph, too.

**Comment by guettli** [comment]
I think this is implemented now: https://syself.com/docs/caph/getting-started/introduction
