### ISSUE TITLE
Custom resource definitions for CAPH

### ISSUE THREAD

**Issue by Sayanta66** [syself/cluster-api-provider-hetzner#1157]
- The `reference` section of the CAPH documentation contains the description of the CAPH CRDs. Compare the `reference` section with the [Crd.dev docs](https://doc.crds.dev/github.com/syself/cluster-api-provider-hetzner@v1.0.0-beta.28) and fill out the gaps in the API documentation.
- Migrate entirely to the [CRD.devs docs](https://doc.crds.dev/github.com/syself/cluster-api-provider-hetzner@v1.0.0-beta.28) for API reference, once its updated completely.

**Comment by Sayanta66** [comment]
Description missing from CRDs:

kind: HCloudMachine
spec - placementGroupName, enableIPv4, enableIPv6

**Comment by Sayanta66** [comment]
@janiskemper - The above specs are without descriptions in the CRD docs.

**Comment by Sayanta66** [comment]
#1178

**Comment by guettli** [comment]
> #1169 #1170 #1172 #1175 #1177 #1178 #1179

All mentioned issues are closed. I think this issue can get closed.

Feel free to re-open if you think there is something missing.
