### ISSUE TITLE
HCLOUD_REGION not respected when creating network

### ISSUE THREAD

**Issue by rgarcia** [syself/cluster-api-provider-hetzner#1206]
/kind bug

**What steps did you take and what happened:**
Followed the preparation.md and quickstart.md docs. Changed HCLOUD_REGION to `ash` and used `--flavor hcloud-network`

**What did you expect to happen:**
A cluster to spin up :). Instead I saw a network created in HCloud in eu-central, and errors during load balancer create to use this network (presumably because the load balancer was in `ash`).

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-hetzner version: latest
- Kubernetes version: (use `kubectl version`) v1.29.1
- OS (e.g. from `/etc/os-release`): mac os

**Comment by batistein** [comment]
@rgarcia true Currently we always set it to eu-central. This is from a time when there were no US regions. We @Syself don't use the networking feature at all - which is why we didn't catch this problem earlier.

**Comment by batistein** [comment]
sorry just re-checked the setting could be set in the `networkZone` see: https://github.com/syself/cluster-api-provider-hetzner/blob/0fedc3063e5c0264f10ae48bea3f2cf3b759449e/api/v1beta1/types.go#L216

The default is just `eu-central`

**Comment by rgarcia** [comment]
ok thanks! I will edit the cluster yaml to specify that in the future. Since you're not using the private network I decided to switch away from it and just use the default template. Not successful yet though (#1207)
