### ISSUE TITLE
I created a k8s cluster with cluster api and hezner provider, but the cluster never acheive the working state

### ISSUE THREAD

**Issue by oussamarouabah** [syself/cluster-api-provider-hetzner#1271]
/kind bug

**What steps did you take and what happened:**
I just followed the steps in the quickstart.md document to create the cluster,
created the API key and the SSH key, generated the yaml files for my cluster using this command

```
clusterctl generate cluster my-cluster --kubernetes-version v1.28.1 --control-plane-machine-count=1 --worker-machine-count=2  > my-cluster.yaml
kubectl apply -f my-cluster.yaml
```

wait for the control plane to be up and running and get the kubeconfig
```
export CAPH_WORKER_CLUSTER_KUBECONFIG=<path>
clusterctl get kubeconfig my-cluster > $CAPH_WORKER_CLUSTER_KUBECONFIG
```
deploy the CNI:

```
helm repo add cilium https://helm.cilium.io/
helm repo update
KUBECONFIG=$CAPH_WORKER_CLUSTER_KUBECONFIG helm upgrade --install cilium cilium/cilium --version 1.14.4 \
--namespace kube-system \
-f templates/cilium/cilium.yaml
```

```


**What did you expect to happen:**


I expected the cluster to be ready, but all nodes were tainted with NoSchedule, so coredns didn't get scheduled and the cluster API kept detecting that those worker nodes were not healthy and kept recreating them.



**Environment:**

- cluster-api-provider-hetzner version: v1.0.0-beta-33
- Kubernetes version: (use `kubectl version`) v1.29.1 for the management cluster ( kind ) and 1.28.1 for the workload cluster
- OS (e.g. from `/etc/os-release`): ubuntu 22.04

**Comment by kranurag7** [comment]
I think you missed CCM, can you please deploy CCM as well. 

https://github.com/syself/cluster-api-provider-hetzner/blob/main/docs/topics/quickstart.md#deploy-hcloud-cloud-controller-manager---hcloud-only 

Please ask if something is not clear or something doesn't work out as expected.

**Comment by oussamarouabah** [comment]
Yes, that solves the issue using k8s 1.27.8, the things are I recall I tried this with 1.29 and it didn't work, so what I will do is try to build new clusters with a different version of Kubernetes and see where it breaks and where its not breaking.

Thanks @kranurag7 for the support

**Comment by oussamarouabah** [comment]
@oussamarouabah oh it worked but not the ltest version which is 1.29.4 but 1.29.3 worked which is more than enough for me, thanks again @kranurag7
