### ISSUE TITLE
imageName in HCloudMachine doesnt work with snapshots

### ISSUE THREAD

**Issue by kanwar-saad** [syself/cluster-api-provider-hetzner#128]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](../../docs/topics/troubleshooting.md)]
Yes
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I have created a simple hcloudMachineTemplate. it has an imageName field. this name doesn't work with snapshots since snapshots in hcloud don't have a name. Snapshots are only created with a description, id or optional labels. 

infrastructureprovider controller throws the following error if and id, description or labels are given in imageName field.

`
{"level":"ERROR","time":"2022-03-19T01:08:55.839Z","logger":"controller.hcloudmachine","file":"controller/controller.go:317","message":"Reconciler error","reconciler group":"infrastructure.cluster.x-k8s.io","reconciler kind":"HCloudMachine","name":"my-cluster-control-plane-mwtmn","namespace":"hcloud","error":"failed to reconcile server for HCloudMachine hcloud/my-cluster-control-plane-mwtmn: failed to create server: failed to get server image: no image found with name testImage","errorVerbose":"no image found with name testImage\nfailed to get server image\ngithub.com/syself/cluster-api-provider-hetzner/pkg/services/hcloud/server.(*Service).createServer\n\t/workspace/pkg/services/hcloud/server/server.go:175\ngithub.com/syself/cluster-api-provider-hetzner/pkg/services/hcloud/server.(*Service).Reconcile\n\t/workspace/pkg/services/hcloud/server/server.go:75\ngithub.com/syself/cluster-api-provider-hetzner/controllers.(*HCloudMachineReconciler).reconcileNormal\n\t/workspace/controllers/hcloudmachine_controller.go:185\ngithub.com/syself/cluster-api-provider-hetzner/controllers.(*HCloudMachineReconciler).Reconcile\n\t/workspace/controllers/hcloudmachine_controller.go:146\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581\nfailed to create server\ngithub.com/syself/cluster-api-provider-hetzner/pkg/services/hcloud/server.(*Service).Reconcile\n\t/workspace/pkg/services/hcloud/server/server.go:77\ngithub.com/syself/cluster-api-provider-hetzner/controllers.(*HCloudMachineReconciler).reconcileNormal\n\t/workspace/controllers/hcloudmachine_controller.go:185\ngithub.com/syself/cluster-api-provider-hetzner/controllers.(*HCloudMachineReconciler).Reconcile\n\t/workspace/controllers/hcloudmachine_controller.go:146\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581\nfailed to reconcile server for HCloudMachine hcloud/my-cluster-control-plane-mwtmn\ngithub.com/syself/cluster-api-provider-hetzner/controllers.(*HCloudMachineReconciler).reconcileNormal\n\t/workspace/controllers/hcloudmachine_controller.go:186\ngithub.com/syself/cluster-api-provider-hetzner/controllers.(*HCloudMachineReconciler).Reconcile\n\t/workspace/controllers/hcloudmachine_controller.go:146\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:317\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227"}
`

**What did you expect to happen:**
Image should be selectable using an Id, description or labels. It is a common usecase to pre-build kubernetes images and use them with clusterapi instead of using default system images and doing installations during image provisioning.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-hetzner version: 
- Kubernetes version: (use `kubectl version`)
- OS (e.g. from `/etc/os-release`):

**Comment by kanwar-saad** [comment]
after reading the code, i found that the label should be of the format `caph-image-name=myCustomImage` and give `myCustomImage` in the `imageName` field instead of whole label.

This should be documented somewhere.

**Comment by batistein** [comment]
@kanwar-saad Thank you very much for your issue! In general this is documented here: https://github.com/syself/cluster-api-provider-hetzner/blob/main/docs/developers/development.md#caph-node-images

But you're right that it's not very obvious under development. I think a separate document for the use of own machine images would be more helpful? 
Feel free to improve the documentation yourself with a PR, we would be very happy about that.
