### ISSUE TITLE
confusing hcloudmachinetemplate controller error when using k0s

### ISSUE THREAD

**Issue by rgarcia** [syself/cluster-api-provider-hetzner#1291]
/kind bug

**What steps did you take and what happened:**
Please see here: https://github.com/k0sproject/k0smotron/issues/561

 Basically I'm trying to run the basic k0s cluster-api + hetzner example from their [docs](https://docs.k0smotron.io/stable/capi-hetzner/) and running into a lot of problems. I've tracked it down to the CAPH machinetemplate controller failing to create the machine template because it can't fetch the hcloud api key secret from the parent hetznercluster object... but that seems to be configured correctly, so I'm stumped.

**What did you expect to happen:**
A k0s cluster to spin up in hetzner.

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-hetzner version: v1.0.0-beta.32
- Kubernetes version: (use `kubectl version`) v1.29.3
- OS (e.g. from `/etc/os-release`):  mac os

**Comment by guettli** [comment]
I never used k0s, but I use caph daily and it works fine. 

Why do you use k0s? I don't know that project. 

Have you tried using caph the normal way (start with the mgt cluster in a kind cluster, later you can move the mgt cluster into a wl cluster)?

**Comment by rgarcia** [comment]
Yes I am using caph the normal way daily as well! I'm using a regular old kubeadm cluster in Hetzner as my management cluster and have used it to create lots of clusters.

I'm now trying to make some extremely lightweight k0s clusters for users and so that put me down the path of trying to get caph to work with the k0s control plane provider. So any guidance on how to debug caph in this case would be greatly appreciated.

**Comment by guettli** [comment]
If the secret can't be found, these things come to my mind: 

Check the namespace.

Check rbacs via impersonating the service account.

**Comment by batistein** [comment]
@rgarcia Were you able to solve it?

**Comment by rgarcia** [comment]
I gave up and switched back to default control plane provider in CAPH (kubeadm). It's working fine for now. I do think it would be nice to get a lightweight control plane provider like k0s or k3s working, since Hetzner is often the place people go for super low-cost VMs. E.g. running a single node k0s cluster on a cax11 would be neat.

Thanks for checking in and feel free to close.

**Comment by guettli** [comment]
thank you for your feedback. Feel free to open a new issue if something is not working or not easy to understand.
