### ISSUE TITLE
Setting up a basic Firewall on the Cilium side in K8s Cluster CAPI

### ISSUE THREAD

**Issue by BigBrather** [syself/cluster-api-provider-hetzner#1325]
/kind bug

**What steps did you take and what happened:**

I did not find a basic Firewall setup using Cilium in this repository.

**What did you expect to happen:**

I expect that in the end I will be able to close the K8s Cluster created using CAPI using Cilium under the basic Firewall.

**Anything else you would like to add:**

I would like to get the basic Firewall configuration for Cilium in your version from CAPI, or better yet, a configuration file, because by default we do not close the Firewall when installing K8s Cluster using the CAPI solution.

**Environment:**

- cluster-api-provider-hetzner version: v1.0.0-beta.33
- Kubernetes version: (use `kubectl version`): v1.28.7
- OS (e.g. from `/etc/os-release`): ubuntu-22.04

**Comment by batistein** [comment]
@BigBrather The reason for this is that the firewall depends heavily on your setup. So these kinds of things are out of scope, see also: https://github.com/syself/cluster-api-provider-hetzner?tab=readme-ov-file#-clarifying-scope

**Comment by BigBrather** [comment]
I need a basic setup for the Cilium Firewall, not for my installation.

**Comment by BigBrather** [comment]
@batistein I need a basic setup for the Cilium Firewall, not for my installation. But, if CAPI does not have a basic configuration for the CAPI firewall. I'll close this issue.

**Comment by guettli** [comment]
@BigBrather Configuring a Cilium Firewall is explained in the docs of Cilium: https://docs.cilium.io/en/latest/security/host-firewall/

If you have question about that, please ask at their preferred community channel (afaik Slack). 

I close this issue, since I think it is not related to caph.

Feel free to re-open it if you disagree, or open a new issue, if caph is not working for you (or something is not easy to understand).

**Comment by BigBrather** [comment]
@guettli I disagree that I didn't get an answer like this (does CAPH do basic setup for Cilium when first deployed):
- This is not the case; when deployed, we receive an open K8s Cluster firewall, where FIreWall is configured separately according to the Cilium documentation.

Thanks for your answer.
