### ISSUE TITLE
:book: Add missing page for hcloud template remediation

### ISSUE THREAD

**Issue by buhodev** [syself/cluster-api-provider-hetzner#1345]
The second link on this line https://github.com/syself/cluster-api-provider-hetzner/blob/f90301dee65e77d8de5ca8fcfd7924345e8d0ba8/docs/topics/advanced-caph.md?plain=1#L31 is referencing a `/docs/reference/hcloud-remediation-template.md` file that doesn't exist.

There is a file for baremetal (https://github.com/syself/cluster-api-provider-hetzner/blob/main/docs/reference/hetzner-bare-metal-remediation-template.md) but not for hcloud.

**Comment by janiskemper** [comment]
We can copy paste and replace HetznerBareMetalMachine with HCloudMachine. It's the same

**Comment by guettli** [comment]
I tested the hyperlink here: https://syself.com/docs/caph/topics/advanced/custom-templates-mhc

And it works fine. Looks solved.
