### ISSUE TITLE
Support for the new cloud servers

### ISSUE THREAD

**Issue by PlayMTL** [syself/cluster-api-provider-hetzner#1366]
> ⚠️ Cluster API Hetzner maintainers can ask to turn an issue-proposal into a [CAEP](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/YYYYMMDD-template.md) when necessary. This is to be expected for large changes that impact multiple components, breaking changes, or new large features.

***Goals***
Hetzner reworked their Intel based cloud server lineup (https://www.hetzner.com/cloud/). (Also looks like they deprecated some of their old configs, but they are still available via api). The goal is to support the new cloud server configurations:
- CX22
- CX32
- CX42
- CX52

**User Story**

As a user I would like to use the new intel cloud server lineup for my capi cluster.

**Detailed Description**

The new server types should be configurable and usable for the endusers of the provider. I found a validation string which might need to be updated: https://github.com/syself/cluster-api-provider-hetzner/blob/e6e5e7710a0bcd646a332a03273268c24f2cb5f7/api/v1beta1/hcloudmachine_types.go#L40

**Contract changes [optional]**
%

**Data model changes [optional]**
%

/kind proposal

**Comment by kranurag7** [comment]
No worries at all. Please open issues anytime if something doesn't work right. 

FYI, we have launched new docs today at https://caph.syself.com/ which might be helpful to you if you're using CAPH. (I'll try to get the server type added into the docs as well)
