### ISSUE TITLE
Ubuntu 24.04 does not work with the installimage, but hetzner official installimage works fine

### ISSUE THREAD

**Issue by ashish1099** [syself/cluster-api-provider-hetzner#1382]
/kind feature

**Describe the solution you'd like**
Update installimage to support 24.04

**Comment by kranurag7** [comment]
Hey Ashish,
thanks for opening the issue, we use the installimage from https://github.com/syself/hetzner-installimage repository which is a fork of upstream https://github.com/hetzneronline/installimage 

upon checking the diff (https://github.com/syself/hetzner-installimage/compare/master...hetzneronline%3Ainstallimage%3Amaster), I noticed that there's nothing in the upstream that's added separately for Ubuntu 24.04.

Please point me out on how this could be solved by updating the installimage. If I didn't missed anything, this should work out of the box. Can you please paste the specific error that you're getting if that's the case? 

Having said that, If you think that updating the installimage would fix the problem then can you please verify it once? You'll require to clone the repo, update installimage in the repository and build the CAPH image using `docker build -t ghcr.io/<username>/caph -f images/caph/Dockerfile .` and replace the image at runtime.

**Comment by guettli** [comment]
@ashish1099 you are right, our install-image fork was a bit out of date.

I merged 6 upstream commits into our fork: https://github.com/syself/hetzner-installimage/pull/6

The PR in caph: https://github.com/syself/cluster-api-provider-hetzner/pull/1440

I looked at the changes, and I don't think this will make it a difference.

I will close this issue. Please create a new issue if you still have problems.
