### ISSUE TITLE
syself/ccm-hcloud fails to start after install

### ISSUE THREAD

**Issue by madbbb** [syself/cluster-api-provider-hetzner#1399]
/kind bug

**What steps did you take and what happened:**
I was following documentation to deploy 3 control-lanes of cax11 and 3 cax31 workers, after it created first cp node I deployed CNI and started installing ccm as per docs:
```
KUBECONFIG=$CAPH_WORKER_CLUSTER_KUBECONFIG helm upgrade --install ccm syself/ccm-hcloud --version 1.0.11 --namespace kube-system --set secret.name=hetzner --set secret.tokenKeyName=hcloud --set privateNetwork.enabled=false
```
I see that ccm is fails to start:
```
❯ KUBECONFIG=$CAPH_WORKER_CLUSTER_KUBECONFIG k -n kube-system get po
NAME                                                    READY   STATUS    RESTARTS      AGE
ccm-ccm-hcloud-7f595cd55-9v8sn                          0/1     Error     4 (46s ago)   93s
cilium-9r5n2                                            1/1     Running   0             3m41s
cilium-bw8d2                                            1/1     Running   0             2m45s
cilium-lgnvl                                            1/1     Running   0             111s
cilium-operator-7d454cf4cc-9c294                        1/1     Running   0             3m41s
cilium-operator-7d454cf4cc-qskx2                        1/1     Running   0             3m41s
```

Logs:
```
❯ KUBECONFIG=$CAPH_WORKER_CLUSTER_KUBECONFIG k -n kube-system logs ccm-ccm-hcloud-7f595cd55-9v8sn
Error from server: no preferred addresses found; known addresses: []
```

The only way for me to provision cluster further was installing hcloud/hcloud-cloud-controller-manager
```
KUBECONFIG=$CAPH_WORKER_CLUSTER_KUBECONFIG helm upgrade ccm hcloud/hcloud-cloud-controller-manager --namespace kube-system --set secret.name=hetzner --set secret.tokenKeyName=hcloud --set env.HCLOUD_TOKEN.valueFrom.secretKeyRef.name=hetzner --set env.HCLOUD_TOKEN.valueFrom.secretKeyRef.key=hcloud
```

**What did you expect to happen:**
Expected syself/ccm-hcloud to run.

**Anything else you would like to add:**
What's the difference between yours and Hetzner CCM?

**Environment:**

- cluster-api-provider-hetzner version: 
- Kubernetes version: 1.29.4
- OS (e.g. from `/etc/os-release`):

**Comment by guettli** [comment]
@madbbb which docs are you reading? Please send me the link.

In the README I see:

```
helm repo add hcloud https://charts.hetzner.cloud
helm repo update hcloud
helm install hccm hcloud/hcloud-cloud-controller-manager -n kube-system
```

**Comment by guettli** [comment]
@madbbb if you only want to use hcloud, and not bare-metal, then it is best to use the upstream ccm of hcloud. 

Thank you for pointing us to a broken to documentation:

This (source of your above command) is outdated:

https://github.com/syself/cluster-api-provider-hetzner/blob/main/docs/caph/01-getting-started/02-quickstart/03-creating-a-workload-cluster.md?plain=1#L103

**Comment by madbbb** [comment]
@guettli thanks for response! lets close the ticket
