### ISSUE TITLE
Fix links in CAPH docs/README

### ISSUE THREAD

**Issue by janiskemper** [syself/cluster-api-provider-hetzner#1400]
/kind bug

**What steps did you take and what happened:**
Some links are still broken, namely in docs/README.md.

**What did you expect to happen:**
Fix all links in docs/README.md and test other links and see whether they work.

**Comment by guettli** [comment]
@janiskemper I checked the links in doc/README.md (in vscode with ctrl-click), and it looks good. I found no broken link in that file. Please close the issue our explain which link is still broken.

**Comment by janiskemper** [comment]
@guettli there was a PR that wasn't linked to this issue. Would be great if you can do that!

**Comment by guettli** [comment]
This issue got fixed via https://github.com/syself/cluster-api-provider-hetzner/pull/1406
