### ISSUE TITLE
Handle install-image asynchronously

### ISSUE THREAD

**Issue by guettli** [syself/cluster-api-provider-hetzner#1408]
/kind feature

**Describe the solution you'd like**

I want the `Reconcile()` calls in Go to finish quickly, so that the reconciling of other events is not blocked.

At the moment the install-image phase takes roughly 2.5min. During that time the controller does not reconcile
other events.

We want to call install-image asynchronously like this:

```
ssh user@remote_host 'nohup my_command > output.log 2>&1 < /dev/null &'
```

Additionally, we should log a warning, if a reconcile call takes longer than 15 seconds.

**Comment by janiskemper** [comment]
one little addition: The controller can be configured to be used in parallel. Having such a long blocking operation is an anti-pattern in general
