### ISSUE TITLE
Wrong values in hetzner ccm quickstart docs for hcloud only clusters

### ISSUE THREAD

**Issue by timkrase** [syself/cluster-api-provider-hetzner#1444]
/kind bug

**What steps did you take and what happened:**
Tried to install the hetzner ccm in a hcloud only cluster. Since #1415 , the helm command in the docs looks like this: 
`helm repo add hcloud https://charts.hetzner.cloud
helm repo update hcloud

KUBECONFIG=$CAPH_WORKER_CLUSTER_KUBECONFIG helm upgrade --install hccm hcloud/hcloud-cloud-controller-manager --version 1.20.0 \
  --namespace kube-system \
  --set secret.name=hetzner \
  --set secret.tokenKeyName=hcloud \
  --set privateNetwork.enabled=false`

Unfortunately, this does not seem to work, as the secret is not correctly initialized. The container therefore fails to be created. 
Following [Management cluster setup](https://syself.com/docs/caph/getting-started/quickstart/management-cluster-setup) of the docs, the secret is created with the name "hetzner" and key "hcloud". Hetzner ccm expects a secret with name "hcloud" and key "token" though by default ([hetzner ccm values.yaml](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/chart/values.yaml). 

I ended up installing ccm with the following helm command: `helm upgrade --install hccm hcloud/hcloud-cloud-controller-manager -n kube-system --version 1.20.0   --namespace kube-system   --set env.HCLOUD_TOKEN.valueFrom.secretKeyRef.name=hetzner   --set env.HCLOUD_TOKEN.valueFrom.secretKeyRef.key=hcloud`

It was just a quick test from my side, I don't know how/if the private network value needs to be adjusted too.

**Comment by guettli** [comment]
I am reproducing it, and can confirm:

```
kube-system   65s         Warning   Failed                    pod/hcloud-cloud-controller-manager-66d499b786-cd8pp         Error: secret "hcloud" not found
```
