### ISSUE TITLE
Update to CAPI 1.8

### ISSUE THREAD

**Issue by guettli** [syself/cluster-api-provider-hetzner#1448]
/kind feature

**Describe the solution you'd like**

Cluster API 1.8 was released some days ago. We should upgrade to that version.

[docs 1.7 --> 1.8](https://cluster-api.sigs.k8s.io/developer/providers/migrations/v1.7-to-v1.8)

**Comment by janiskemper** [comment]
https://github.com/syself/cluster-api-provider-hetzner/pull/1485
