### ISSUE TITLE
Add flag to disable the default CSR Reconciler

### ISSUE THREAD

**Issue by xaverkapeller** [syself/cluster-api-provider-hetzner#1478]
/kind feature

**Describe the solution you'd like**

There should be an option to disable the default CSR reconciler. The reconciler included with the Hetzner ClusterAPI provider validates that nodes in the Kubernetes Cluster use Hetzner-provided external/internal IP addresses, which is not necessarily true for all use cases.

Depending on the configuration of the Kubernetes cluster it is possible that completely different IPs are used by Kubernetes internally, or even externally, e.g. if a mesh VPN service or something similar is used for node IPs.

Adding configuration options to the `CSRReconciler` to accommodate all those use-cases does not seem feasible, but disabling it to allow users to deploy their own custom `CSRReconciler` is quite simple.

Of course the responsibility to securely validate the CSRs would then fall onto the cluster admin who disabled the default `CSRReconciler`. 

**Anything else you would like to add:**

I can provide an implementation of this feature, but I'm unsure about how exactly I should integrate it into the existing automated tests, since this would require a replacement CSR reconciler service to be deployed for the e2e tests.

The simplest version of this change is to make the lines 711-724 in the `hetznercluster_controller.go` conditional with a flag, for example:

```go
if !r.DisableCSRReconciler {
	gr := &GuestCSRReconciler{
		Client: clusterMgr.GetClient(),
		mCluster: &managementCluster{
			Client:         r.Client,
			hetznerCluster: hetznerCluster,
		},
		WatchFilterValue: r.WatchFilterValue,
		clientSet:        clientSet,
		clusterName:      clusterScope.Cluster.Name,
	}

	if err := gr.SetupWithManager(ctx, clusterMgr, controller.Options{}); err != nil {
		return nil, fmt.Errorf("failed to setup CSR controller: %w", err)
	}
}
```

I already have a fork with pretty much exactly this change deployed and it's running without issues.

**Environment:**

- cluster-api-provider-hetzner version: 
- Kubernetes version: (use `kubectl version`)
- OS (e.g. from `/etc/os-release`):

**Comment by guettli** [comment]
@xaverkapeller Hi Xaver, thank you for your feature request. Just out of curiosity: How do you use caph and how do you plan to approve the CSRs?

Overall I would like that feature to get implemented. As you mentioned there are two ways to solve that:

Option 1: We provide a flag to the controller like (--disable-csr-approval). This is easier to implement, but it has the drawback, that it affects all clusters managed by the controller.

Option 2: Put it into the HetznerCluster CRD Spec. This has the benefit that you can differentiate. Some cluster can use the default, and some clusters can have the csr approval disabled.

Option 3: We use an annotation on HetznerCluster. 

@xaverkapeller do my above lines fit to your thoughts - do you see other options?

@janiskemper what do you think?

**Comment by janiskemper** [comment]
It sounds to me as if @xaverkapeller or people that would like to have this feature potentially are not necessarily interested to differentiate the behavior on cluster level, but rather implementing their own operator to handle these cases. 

I'm open to both, but I suppose that the solution outlined by @xaverkapeller above is enough already.

**Comment by guettli** [comment]
ok, then @xaverkapeller please create a PR.

**Comment by xaverkapeller** [comment]
We use caph just to provision servers in the Hetzner Cloud. On boot the nodes join a mesh VPN where they get an internal IP. To facilitate this we have developed an operator which essentially builds on top of caph.
It handles everything aside from provisioning the servers and talking to the Hetzner API, and is among other things responsible for validating/approving the CSRs.

@janiskemper is correct, we currently only need a toggle to enable/disable this feature globally for the entire management cluster. But I'm perfectly fine with adding a field in the CRD as well. I just assumed you wouldn't want to add a field in the CRD for what could be considered a niche use case.

If you'd prefer a field in the CRD I'd be happy to create a pull request for that as well.

**Comment by janiskemper** [comment]
I would be fine with a PR to disable the CSR controller!
