### ISSUE TITLE
#1150 breaks if control plane provider doesn

### ISSUE THREAD

**Issue by mstarostik** [syself/cluster-api-provider-hetzner#1494]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-hetzner version: 
- Kubernetes version: (use `kubectl version`)
- OS (e.g. from `/etc/os-release`):

**Comment by janiskemper** [comment]
superseded by https://github.com/syself/cluster-api-provider-hetzner/issues/1496
