### ISSUE TITLE
This issue tracks Hetzner dedicated servers coming soon Proposal

### ISSUE THREAD

**Issue by gc-ss** [syself/cluster-api-provider-hetzner#154]
Love what this allows us to do on hcloud.

I am particularly excited to see `Hetzner dedicated servers coming soon`. Creating this issue to track that discussion/work. Hope this is OK.

There's already an exciting startup that's running Kubernetes on Hetzner root/dedicated servers. Here's their roadmap:  https://docs.symbiosis.host/about/roadmap

I am unsure how close their OSS contributions brings us closer to running Kubernetes on Hetzner root/dedicated servers

- https://github.com/symbiosis-cloud/symbiosis-k8s-controller
- https://github.com/symbiosis-cloud/csi-driver-symbiosis-block

I sketched out a way how I would go about it: https://www.reddit.com/r/hetzner/comments/ttm3n7/how_do_you_manage_hetzner_robot_resources_like/i3d0g8w/

**Comment by batistein** [comment]
Hi @gc-ss we are right now in testing stage for robot. And in the next weeks we will merge it.

**Comment by gc-ss** [comment]
That's excellent news 👍

Hope this is OK as an issue to track that discussion/work - say when it's released?

Can't wait to try it out

**Comment by batistein** [comment]
sure thank you for opening this tracking issue ;) Happy to hear that! We will announce it when it's ready.

**Comment by janiskemper** [comment]
Hi @gc-ss, we didn't know Symbiosis until now. Thanks for the links! From the first glance I would say that the first difference is that the Cluster API and its provider integrations (including this one) are Infrastructure As Software, whereas Symbiosis uses Terraform, i.e. Infrastructure as Code. These two approaches are fundamentally different in my eyes. 

Without having gone through all the details, I saw that their k8s-provider includes a CSR controller similar to the one we included built. This is a nice feature to run e.g. metrics server in a secure mode. 

Regarding the CSI driver: We use the standard CSI driver of Hetzner if Hetzner volumes should be used.

**Comment by batistein** [comment]
We just released Bare Metal Support!!! Please check it out. https://github.com/syself/cluster-api-provider-hetzner/releases/tag/v1.0.0-alpha.17 If you have any questions or issues feel free to open an issue.

I will close this tracking Issue therefore.
