### ISSUE TITLE
docs/topic/troubleshooting.md does not exist

### ISSUE THREAD

**Issue by guettli** [syself/cluster-api-provider-hetzner#201]
/kind bug

I see this in the new issue template:

> Before submitting an issue, have you checked the [Troubleshooting Guide](../../docs/topics/troubleshooting.md)

But this file `docs/topics/troubleshooting.md` does not exist.

**Comment by batistein** [comment]
good finding! Right now we don't have any topics for a troubleshooting guide. 
I would suggest to remove this line or we should make a collection of possible topics here.
