### ISSUE TITLE
Making controlPlaneLoadBalancer optional?

### ISSUE THREAD

**Issue by BlakeB415** [syself/cluster-api-provider-hetzner#229]
/kind feature

**Describe the solution you'd like**
Would it be possible to make the controlPlaneLoadBalancer parameter optional? There are some cases where I don't need the hetzner load balancer.

**Comment by batistein** [comment]
Could you please describe two use cases (user-stories) ? We would like to use this as a tracking issue for that feature.

**Comment by BlakeB415** [comment]
We have staging environments that do not necessarily require high availability on the control plane as we only have one control plane node in those deployments.
Another use case would be setting up our own load balancer outside of the hcloud provided one.

**Comment by BlakeB415** [comment]
Would it be possible to have it use the first control plane's IP by default instead of having to define an A record, or is there some technical limitation there with the lifecycle?

**Comment by batistein** [comment]
The cluster API uses servers as caddies. So, by using the first control plane IP directly, this would only be valid until the control plane is updated. The SAN field of the certificate will become invalid thereafter because the IP address changes when a new control plane node is created.

**Comment by BlakeB415** [comment]
> The cluster API uses servers as caddles. So, by using the first control plane IP directly, this would only be valid until the control plane is updated. The SAN field of the certificate will become invalid thereafter because the IP address changes when a new control plane node is created.

That makes sense. Thank you for explaining!
