### ISSUE TITLE
IPv6 Only/Dual Stack support?

### ISSUE THREAD

**Issue by BlakeB415** [syself/cluster-api-provider-hetzner#233]
/kind feature

**Describe the solution you'd like**
Hetzner recently added a feature to allow IPv6-only VMs on HCloud. IPv4s are now considered an extra cost for each instance.
Is there currently a way to do IPv6 Only or Dual Stack deployments? I haven't seen any documentation on this anywhere so I assume not.

**Comment by batistein** [comment]
Dual stack is already possible. You have to add in the Cluster CR .spec.clusterNetworks.pods.cidrBlocks, .spec.clusterNetworks.services.cidrBlocks and in the KubeadmControlPlane CR cluster-cidr. I will add a cluster-template and some test later if I have some time.

Ipv6 only should work similar to this, but of course right now there is no logic implemented to get a server without Ipv4 Adress. We could add a spec for that in the machineTemplate @janiskemper  https://docs.hetzner.cloud/#servers-create-a-server
