### ISSUE TITLE
using on 3x physical servers and sw raid 1?

### ISSUE THREAD

**Issue by KlavsKlavsen** [syself/cluster-api-provider-hetzner#287]
/kind feature

**Describe the solution you'd like**
We are running k8s clusters, run up by puppet currently, which are setup like this:
software raid 1 on nvme disks (fast but smaller) and on hdd disks (slow but large)
and we put OS on a small seperate sw raid1 on HDD - and rest is just unpartitioned disk, grabbed by Ceph.
we then setup rook/ceph to use HDD (with 1gb interface, fast disks is not gonna work anyways for ceph) - and then we setup localzfs storageclass for nvme disks, and use those for HA postgres-operator clusters (with HA in operator it handles failover and data sync in app - so local disk is best and fast).
We then use the hetzner docker image, that manages a floating ip - and points it to the node on which it is running - creating a HA bare metal cluster, where floating ip is simply moved to diff. node - if active ingress server dies
.
I am trying to figure out, how to use this to roll out such a cluster setup on 3 new bare metal servers with hetzner.. ?

**Comment by batistein** [comment]
@KlavsKlavsen thank you very much for opening the issue!
Unfortunately, I'm not sure what exactly the feature request and/or question is.

Currently you can do exactly the same thing through installimage, leave one disk for the OS and the other disks unpartitioned. Instead of a floating IP one would then use an ingress or a service of the type loadbalancer if it should be accessible from the outside. Internally you can also simply link this with the svc. The svc and operator will usually do the failover from primary to replica etc.

**Comment by KlavsKlavsen** [comment]
I am trying to follow this ( https://cluster-api.sigs.k8s.io/user/quick-start.html ), to setup cluster-api (on existing cluster) - so I can then use it to create the above cluster - but I am very unclear about how to actually do that - with cluster-api and this plugin/provider.. I cannot seem to find docs/examples that helps me :(

As I understand the docs, I need to have unprovisioned servers from hetzner, running rescue image - and then this plugin will run install, and hence also setup software raid etc. ?

**Comment by batistein** [comment]
Please see also: https://github.com/syself/cluster-api-provider-hetzner/blob/main/docs/topics/quickstart.md
There are the steps described

**Comment by batistein** [comment]
You need an unprovisioned server - thats right, then you need to decide which disk you want to use for the OS. This could be either done by jumping manually into the rescue system and grapping the wwn and then put in the HetznerBareMetalHost or by following this: https://github.com/syself/cluster-api-provider-hetzner/blob/main/docs/reference/hetzner-bare-metal-host.md
On the first provisioning the caph provider will get all informations and store it in the status of the object.

**Comment by KlavsKlavsen** [comment]
how do I tell it to setup a software raid1 ? and to use 2  parttions for this? Do I have to manually partition, or ? do a software raid disk, have a WWN number?

**Comment by batistein** [comment]
This is done in the HetznerBareMetalMachineTemplate when you use the machine e.g provision a cluster. The HetznerBareMetalHost object ist just representing a machine item of you inventory.
More information: https://github.com/syself/cluster-api-provider-hetzner/blob/main/docs/reference/hetzner-bare-metal-machine-template.md

**Comment by KlavsKlavsen** [comment]
That does not tell me which command to actually run.
lsblk shows me:
```
 # lsblk 
NAME    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0     7:0    0   3.1G  1 loop 
sda       8:0    0   1.8T  0 disk 
sdb       8:16   0   1.8T  0 disk 
nvme0n1 259:0    0 476.9G  0 disk 
nvme1n1 259:1    0 476.9G  0 disk
```

**Comment by KlavsKlavsen** [comment]
all I can find on WWN numbers, is that they are attached to FC (fiber attached disks) ?

**Comment by batistein** [comment]
@KlavsKlavsen I was just checking again. 
Currently this is not supported as it's not a best practice to run kubernetes on a raid device. Therefore it's deactivated see: https://github.com/syself/cluster-api-provider-hetzner/blob/3211b7aeaf6b8ad0a42176321ac3ee68681396a2/pkg/services/baremetal/host/utils.go#L32

Also the hetznerbaremetaltemplate creating the autosetup config for installimage is only handling the os disk. All other disk stay unprovisioned so that rook/ceph or longhorn for example can use it. Replication is then done by these storage controllers.

**Comment by KlavsKlavsen** [comment]
AFAIK kubeadm does not care if root device is on a software raid or hardware raid  - are recommending people install on servers, with ZERO redundancy for OS disks?

**Comment by KlavsKlavsen** [comment]
since I only have 4 disk slots, I split the HDD into 2 partitions.. 1 for OS (typicly use around 50GB) and rest we lave..
these options for hetzner installer:
```
SWRAID 1
SWRAIDLEVEL 1
HOSTNAME serversname
PART /boot ext3 512M
PART lvm vg0 all
LV vg0 root / ext4 10G
LV vg0 tmp /tmp ext4 1G
LV vg0 var /var ext4 55G
```

**Comment by KlavsKlavsen** [comment]
It would be cool if it supported the installer config from above, to install OS

**Comment by batistein** [comment]
If the disk fails the node will be not-ready (i would recommend to use NPD) and machine health checks could create a new one.

Independently of this, of course, this can be implemented, thank you for sharing the configuration.
The DRIVE configuration is missing, isn't it? 

We would probably have to first enable more than one device to be marked as a drive. Then we can add SWRAID and SWRAIDLEVEL quite easily.

**Comment by KlavsKlavsen** [comment]
and btw. with hetzner - they  use none enterprise disks (which is fine) but it does mean that disks do die a bit more often - we have hit that many times - but as we run software raid 1 - k8s clusters are not affected, we simply get an alert about disk failing soon (smart error) or failed (if we did not react to smart error in time) - inform hetzner to replace disk, and cordone the k8s host, until hetzner have replaced disk and rebooted it - at which time we add the new disk to the software raid, and we are redundant again, and can re-enable the node.

**Comment by batistein** [comment]
I guess this workflow with uncordon and wait until hetzner replaced the disk will not work with machineHealthChecks. But you can set the machine in [maintenance mode](https://github.com/syself/cluster-api-provider-hetzner/blob/main/docs/reference/hetzner-bare-metal-host.md#overview-of-hetznerbaremetalhostspec) and it is completely removed from the cluster so that it is not in the active pool of machines for the time.

**Comment by KlavsKlavsen** [comment]
machine health check cannot fix a broken disk on physical server. and cannot order a new physical server to fix it :) and loosing an entire server, just because a disk failied seems very unnecessary :) - as opposed to being able to do a planned disk-replacement :)

reg. DRIVE - yes you need to ONLY list the drives it SHOULD use - but installer uses the names as given in lsblk - so IMHO best way, would be to simply ask for type of disk to use for OS (HDD, SDD or NVMe) / and that can be gleaned easily in sys - https://www.golinuxcloud.com/check-disk-type-linux/ - and then pick the disks, based on which fullfill the given criteria - and if that - raid1 is selected, fail if there is not 2 disks of the type

**Comment by KlavsKlavsen** [comment]
Since this is not currently supported.. How can I do this manually.. I can install the OS - with raid1 on HDD disks.. but how to I then add those servers to cluster-api, to get it to run kubeadm installer and setup k8s?

**Comment by KlavsKlavsen** [comment]
> I guess this workflow with uncordon and wait until hetzner replaced the disk will not work with machineHealthChecks. 

it should be fairly easy to add.. smartctl locally can tell you if disks are failing.. and if they are - it should be considered unhealthy - and 'it could also check if all software raid devices are in OK state also very simply cat and parse :) - and it could even easily autorepair software raid once new disk is there (no more failed disks) - we just use a command to copy partition layout from current active disk and then add the new partition to the software raid..

So it can be automated.. but IMHO start with making it fail healtcheck if smartctl or software raid says not ok - is a good start..

**Comment by batistein** [comment]
> reg. DRIVE - yes you need to ONLY list the drives it SHOULD use - but installer uses the names as given in lsblk - so IMHO best way, would be to simply ask for type of disk to use for OS (HDD, SDD or NVMe) / and that can be gleaned easily in sys - https://www.golinuxcloud.com/check-disk-type-linux/ - and then pick the disks, based on which fullfill the given criteria - and if that - raid1 is selected, fail if there is not 2 disks of the type

That's in general a very good idea. The only issue I see with this approach is that when you update k8s it's for the controller the same as a new node. When you store data on some disk you don't want that the become the os drive. This is why we right now have the wwn approach. 

And yes I see the point of having an unwanted downtime vs. planned. So it makes sense to add the ability to do swraid for os disk in some cases. 

> > I guess this workflow with uncordon and wait until hetzner replaced the disk will not work with machineHealthChecks.
> 
> it should be fairly easy to add.. smartctl locally can tell you if disks are failing.. and if they are - it should be considered unhealthy - and 'it could also check if all software raid devices are in OK state also very simply cat and parse :) - and it could even easily autorepair software raid once new disk is there (no more failed disks) - we just use a command to copy partition layout from current active disk and then add the new partition to the software raid..
> 
> So it can be automated.. but IMHO start with making it fail healtcheck if smartctl or software raid says not ok - is a good start..

Do you have some examples how this could be done? I'm not that familar with smarctl...

> Since this is not currently supported.. How can I do this manually.. I can install the OS - with raid1 on HDD disks.. but how to I then add those servers to cluster-api, to get it to run kubeadm installer and setup k8s?

I think there is no way to do it right now.

P.S I have already opened an internal ticket for this task ;)

**Comment by KlavsKlavsen** [comment]
> > 
> 
> That's in general a very good idea. The only issue I see with this approach is that when you update k8s it's for the controller the same as a new node. When you store data on some disk you don't want that the become the os drive. This is why we right now have the wwn approach.

But its very easy to see if a disk has been put in use or not - any disk partiioning tool will tell you, if disk is already partitioned and refuse to do it.

It will also detect if Ceph is using the disk AFAIK

why not use UUIDs ? they are unique and stay with the disk - its what fstab uses to ensure it mounts the SAME partition every time - no matter the device name.

it always makes sense to have raid1 on bare metal  OS disks :) - otherwise you will have much higher risk of losing the entire machines capacity on failure, and have to overallocate resources (extra servers at extra cost) - vs. a planned replacement, that can be done at low load times, and hence not interfer - or you could even scale up with hcloud temporarily, while recovering node.

> smartctl example
to report a smartctl alert - hetzner wants the output from: smartctl -a /dev/sda
which shows everything 

we use script from here - to generate textfile collector output for node exporter: http://devel.dob.sk/collectd-scripts/

p.s. thank you for the internal ticket - I would really like to be able to try out cluster-api.. and we mostly have bare metal servers (we only have currently - but I guess I will have to test with hcloud for now).

**Comment by KlavsKlavsen** [comment]
@batistein Sounds great you improved installer options.. I found no changes to any docs in the PR - where can I see how to use this? code seems to still want a WWN for a raid device? (or I may be misreading it) what you have is only device names (sda, sdb or nvme* etc.) - do you have an example of how to use this feature?

**Comment by batistein** [comment]
You still specify the wwn in the HetznerBareMetalHost object see: https://github.com/syself/cluster-api-provider-hetzner/blob/main/docs/reference/hetzner-bare-metal-host.md

The difference is that you can now enter multiple disks. You get the wwn either manually with lsblk -o NAME,SIZE,WWN
or by leaving this unspecified apply the object and then looking into the status of the object (the controller gets all the information from the machine and writes it into the status).
You can now set swraid: 1 in the HetznerBareMetalMachineTemplate under installimage and set the swraidLevel.
The controller then searches for the correct device /dev/sda /dev/sdb and so on. This can also vary between the restarts which is why we use the wwn to ensure that the correct disks are allocated.

**Comment by Privatecoder** [comment]
@batistein I am trying to set up a mixed node cluster (HCloud + Robot) however the bare metal nodes never become available / never get provisioned (always stuck in Provisioning State:  preparing).

I did create thee HetznerBareMetalHost objects and also added rootDeviceHints after fetching wwn via ssh (`lsblk -o NAME,SIZE,WWN`) like so

```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerBareMetalHost
metadata:
  name: "test1" #change
spec:
  serverID: 1234567 #change
  rootDeviceHints:
    raid:
      wwn:
        - "eui.8324fa988998a89" #change
        - "eui. 8324fa988998a90" #change
  maintenanceMode: false
  description: test1 #change
  ```
  
of course I also added the raid settings like so:

```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerBareMetalMachineTemplate
metadata:
  name: my-cluster-md-1
  namespace: default
spec:
  template:
    spec:
      installImage:
        swraid: 1
        swraidLevel: 1
        image:
          path: /root/.oldroot/nfs/install/../images/Ubuntu-2004-focal-64-minimal-hwe.tar.gz
        partitions:
        - fileSystem: ext4
          mount: /boot
          size: 1024M
        - fileSystem: ext4
          mount: /
          size: all
        postInstallScript: |
          #!/bin/bash
          apt-get update && apt-get install -y cloud-init apparmor apparmor-utils
      sshSpec:
        portAfterCloudInit: 22
        portAfterInstallImage: 22
        secretRef:
          key:
            name: sshkey-name
            privateKey: ssh-privatekey
            publicKey: ssh-publickey
          name: robot-ssh
```

and followed the procedures closely multiple times.

Did I get this right: The host must be in a "booted-to-Rescue/Linux" state?

What am I missing?

**Comment by Privatecoder** [comment]
and one more question:

The guide says: # Patch the created secret so it is automatically moved to the target cluster later.

But do we need to patch the `robot-ssh` secret as well?

**Comment by batistein** [comment]
based on the info, it's hard to see a mistake. You write that you are using a mixed setup. Does that mean that the control-planes are in hcloud? And if so are they ready? Are you using the ccm-hetzner? 

Please try if it works without raid activated 

For more information it would be helpful to have cloud-init-output from the server, as well as logs from the caph controller.

> Did I get this right: The host must be in a "booted-to-Rescue/Linux" state?
It doesn't matter in which state the node is. The controller will reconcile it.

Yes that's right the robot-ssh secret would also need to be patched or re-applied when moving the cluster.
Would be happy to see a PR ;)

**Comment by batistein** [comment]
@Privatecoder maybe it could also help to compare your setup with the e2e test in this repo. I have just tested the raid setup which passed: https://github.com/syself/cluster-api-provider-hetzner/actions/runs/3331250559

**Comment by Privatecoder** [comment]
@batistein I still did not get this up and running but am happy to contribute a how-to once I know what I did wrong, but let's start from the very beginning, because the guides [here](https://github.com/syself/cluster-api-provider-hetzner/blob/main/docs/topics/preparation.md) and [here](https://github.com/syself/cluster-api-provider-hetzner/blob/main/docs/topics/quickstart.md) are a bit confusing – at least to me – when it comes to bootstrap-, management-, and workload-clusters.

Some basic questions:

1. Presume I currently have no cluster running: Will I have two clusters, i.e. one management- and one workload-cluster?
2. If so, I guess I would want use `kind` to create a local bootstrap-cluster and use it to create a "real" management-cluster using HCloud machines (probably with the `hcloud-network` flavor).
3. I would then use this _then existing_ management-cluster to create the workload-cluster using the bare-metal and HCloud machines

Is this about right?

**Comment by batistein** [comment]
@Privatecoder please ask these question in discussions. So we can keep the issues structured.

**Comment by Privatecoder** [comment]
@batistein will do and delete them here
