### ISSUE TITLE
Talos github organization was renamed from `talos-systems` to `siderolabs`

### ISSUE THREAD

**Issue by lion7** [syself/cluster-api-provider-hetzner#305]
Just wanted to point out that the github URLs in this repo still point to the old organization.
This organization was renamed a few months ago due to legal reasons, so it would be wise to update the URLs in this repo as well :)

These are the references I could find. Simply replace `github.com/talos-systems` with `github.com/siderolabs`

https://github.com/syself/cluster-api-provider-hetzner/blob/b56ff52be6f69abd787f2b08b3c5e7aabc15ecad/templates/node-image/talos-image/image.json#L32
https://github.com/syself/cluster-api-provider-hetzner/blob/55796e15fee513be8f293cf60874a6edf7cb8153/Tiltfile#L84
https://github.com/syself/cluster-api-provider-hetzner/blob/55796e15fee513be8f293cf60874a6edf7cb8153/Tiltfile#L90

**Comment by batistein** [comment]
Thank you very much for pointing this out! Feel free to make a short PR ;)

**Comment by lion7** [comment]
Done: https://github.com/syself/cluster-api-provider-hetzner/pull/306 😄
