### ISSUE TITLE
Public IPv4 network settings for machine templates apply incorrectly

### ISSUE THREAD

**Issue by EternalDeiwos** [syself/cluster-api-provider-hetzner#312]
/kind bug

After discovering the functionality to disable public network access does exist, I gave it a try and [found it was not applying the configuration correctly](https://github.com/syself/cluster-api-provider-hetzner/issues/312#issuecomment-1277454481). See the comments below.

Also there is a [typo in the documentation](https://github.com/syself/cluster-api-provider-hetzner/issues/312#issuecomment-1277424020).

## Original Request for Optional Public IPv4 addresses for nodes

IPv4 addresses are optional on Hetzner instances and are not strictly necessary when nodes are only intended to be accessible within the cluster and/or external access is always done in front of a load balancer. Alternatively, one might want to exclusively use IPv6 for external access.

It would be nice to recover the expense of IPv4 addresses for pools of nodes that do not strictly need those addresses.

**Environment:**

- cluster-api-provider-hetzner version: 1.0.0-beta.3
- Kubernetes version: 1.25.2
- OS: N/A

**Comment by batistein** [comment]
this is already implemented see: https://github.com/syself/cluster-api-provider-hetzner/blob/main/docs/reference/hcloud-machine-template.md

**Comment by EternalDeiwos** [comment]
The docs for this are incorrect. Docs say the field is: `template.spec.publicNetwork.enabledIPv4` but the [type defs](https://github.com/syself/cluster-api-provider-hetzner/blob/37e06e9499e64bca28f5619ce2239ad03911ddf3/api/v1beta1/types.go#L121) show `template.spec.publicNetwork.enableIPv4`.

Same for IPv6.

**Comment by batistein** [comment]
good catch. this is a typo!

**Comment by batistein** [comment]
feel free to make a PR ;)

**Comment by EternalDeiwos** [comment]
I will if I get it working as it should. Even after the above, for some reason I'm still getting nodes with Public IP addresses allocated to them.

**Comment by EternalDeiwos** [comment]
Am I read this correctly that it would only set the public network options if private networks are disabled? This seems counter-intuitive to me.

https://github.com/syself/cluster-api-provider-hetzner/blob/37e06e9499e64bca28f5619ce2239ad03911ddf3/pkg/services/hcloud/server/server.go#L322-L327

**Comment by batistein** [comment]
the loadbalancer need a public ipv4 address or a private one. so you can disable with network enabled in theory both ipv4 and ipv6 on the public interface..

**Comment by EternalDeiwos** [comment]
Yes but then how do I disable the public address if I _do_ have a private network attached?

**Comment by janiskemper** [comment]
Thanks for pointing this out! You are right that the logic is wrong there. I just created a PR that should fix this!

**Comment by batistein** [comment]
@EternalDeiwos on monday is also a capi patch release after that we will also release the next version with that fix.
