### ISSUE TITLE
talos: machine deployment created too early

### ISSUE THREAD

**Issue by mstarostik** [syself/cluster-api-provider-hetzner#454]
I'm running into a problem with the combination CAPH, CABPT, CACPPT where worker nodes end up in an endless reboot loop and never reach the Ready state.
My HetznerCluster resource has:
```
[...]
spec:
  controlPlaneEndpoint:
    host: ""
    port: 6443
[...]
```
Now, when creating a cluster with at least one worker node, only the control plane nodes are created with bootstrap data that contains a valid endpoint (load balancer IP as expected). Worker node(s) are missing the host:

```
kubectl --context kind-test get secret -l cluster.x-k8s.io/cluster-name=test -o json | jq -r '.items[] | select(.metadata.name | endswith("bootstrap-data")) | [.metadata.name, .data.value] | join(" ")' | while read name data; do echo -n "$name: "; base64 -d <<<$data | yq -r .cluster.controlPlane.endpoint; done
test-controlplane-6v8gn-bootstrap-data: https://XXX.XXX.XXX.XXX:6443
test-controlplane-qw2h6-bootstrap-data: https://XXX.XXX.XXX.XXX:6443
test-controlplane-tb9dz-bootstrap-data: https://XXX.XXX.XXX.XXX:6443
test-md-0-5f6c9b9447-gj6gt-bootstrap-data: https://:6443
```

My assumption is that the workers' bootstrap data is generated before CAPH replaces the empty spec.controlPlaneEndpoint.host value with the LB's external IP.
When creating the cluster with a worker count of 0 and scaling it up later, the bootstrap data is correct and the worker node(s) reach ` Ready`. As it is now, they can never even join. I guess the workers are created too early as they don't depend on the LB creation. Not sure whether this is directly CAPH's fault, but would expect this dependency ordering to be a responsibility of the infrastructure provider. CABPT seems to just happily pick up the empty endpoint and only when booting the node it is flagged as invalid (`Invalid controlplane endpoint: host must not be blank`)

**Comment by janiskemper** [comment]
Just from CAPI perspective, the workers come up after the control plane, don't they? So I don't really understand how the workers can be there before the load balancer and the first control plane is running. Could you explain?

**Comment by mstarostik** [comment]
That would make sense, however I can clearly watch the worker nodes appearing in the hcloud console at the same time or even slightly earlier than the control plane nodes. I can try and grab some logs later.

**Comment by janiskemper** [comment]
I think that would be a good idea! I am sure that nothing will work if workers come before control planes but I have also never seen that happening before.

**Comment by mstarostik** [comment]
Okay, I *think* I found the cause.
Indeed, the MD is created even before the controlplane. All logs support this. This shouldn't be a problem, however as the Talos Bootstrap Provider checks for the cluster's InfrastructureReady status before generating its config and this in turn is a precondition for the HCloudMachine to be reconciled.
However, the control flow at https://github.com/syself/cluster-api-provider-hetzner/blob/main/controllers/hetznercluster_controller.go#L197 looks suspicious to me:

```
	if hetznerCluster.Spec.ControlPlaneLoadBalancer.Enabled &&
		hetznerCluster.Status.ControlPlaneLoadBalancer.IPv4 != "<nil>" {

[...] set endpoint in cluster spec

		hetznerCluster.Status.Ready = true
	} else if hetznerCluster.Spec.ControlPlaneEndpoint != nil {
		hetznerCluster.Status.Ready = true
	}
```
What I ~~suspect~~ found to be happening:
During LB creation, `hetznerCluster.Spec.ControlPlaneLoadBalancer.Enabled` is true, but `hetznerCluster.Status.ControlPlaneLoadBalancer.IPv4 != "<nil>"` is not, so control branches to `else if hetznerCluster.Spec.ControlPlaneEndpoint != nil` which is true because I have a port set in the config. Thus, the LB is treated as disabled and the cluster marked ready so the bootstrap provider does its work based on an incomplete endpoint config.

PR coming up

**Comment by janiskemper** [comment]
Having a deeper look at it: You could have also set it through ControlPlaneLoadBalancer, then everything would have worked (I'm rather sure at least). 

However, when setting the ControlPlaneEndpoint, we assumed in this one line of code you changed that both host and port are set, which is, of course, wrong. [Here](https://github.com/syself/cluster-api-provider-hetzner/blob/main/controllers/hetznercluster_controller.go#L207), we already handled this use case correctly.
