### ISSUE TITLE
bm-node routing broken after cloud-init (wrong gateway, duplicate routes)

### ISSUE THREAD

**Issue by Privatecoder** [syself/cluster-api-provider-hetzner#457]
/kind bug
/lifecycle active

**What steps did you take and what happened:**

- Create a three-node cluster with flavor `hetzner-baremetal-control-planes-remediation` / Ubuntu 20.04 HWE.
- Nodes with IPs within the same subnet – in my case 94.130.10.24 and 94.130.10.27 – won't be able to communicate with each other due to a wrong gateway route-setting:

=> non-working routing after `HetznerBareMetalHost` has finished rebooting and trying to join the cluster:
<img width="570" alt="non-working" src="https://user-images.githubusercontent.com/45964815/202459629-ded4afaf-36ea-44c6-8e68-97dd47cdbfa8.png">

Pinging between the nodes by ssh-ing to either machine (first controlplane and second) does not work `Destination Host Unreachable`.

routing looks like this in rescue-mode:
<img width="552" alt="working-rescue" src="https://user-images.githubusercontent.com/45964815/202458887-57f0d74a-7d98-4a2a-88fd-64894e5b5090.png">

This can be fixed manually by replacing the wrong gateway (`0.0.0.0`):

`route del -net 94.130.10.0 gw 0.0.0.0 netmask 255.255.255.192 enp35s0`
`route add -net 94.130.10.0 gw 94.130.10.1 netmask 255.255.255.192 enp35s0`

also `route del -net 0.0.0.0 gw 94.130.10.1 netmask 0.0.0.0 enp35s0` as the first route is set-up twice.

**What did you expect to happen:**

Correct gateway in routing, no duplicate routes.

**Environment:**

- cluster-api-provider-hetzner version: v1.0.0-beta.7
- Kubernetes version: v1.24.8
- OS: Ubuntu 20.04 HWE

**Comment by Privatecoder** [comment]
While trying to fix the routing manually on all bm-nodes I encountered another issue:

The third of the three nodes receives endless host-reboot-requests via the api until it hits Hetzners rate-limit (`exceeded rate limit with calling robot function RebootBMServer`).

**Comment by janiskemper** [comment]
@batistein will have a look into this

**Comment by Privatecoder** [comment]
As in the other issue: I am happy to re-create the cluster as many times as possibly required to help and debug.

**Comment by Privatecoder** [comment]
for now I added this to `preKubeadmCommands` for bm-(md-1) and control-plane-nodes

```
- export IFACE=$(netstat -i | awk '! /(Kernel|lo|Iface)/ {print $1}')
- export GATEWAY=$(netstat -rn | awk '{if($4=="UH")print $1}')
- export MASK=$(netstat -rn | awk '{if($4=="U")print $3}')
- export NET_IP=$(netstat -rn | awk '{if($4=="U")print $1}')
- route del -net 0.0.0.0 gw $GATEWAY netmask 0.0.0.0 $IFACE
- route del -net $NET_IP gw 0.0.0.0 netmask $MASK $IFACE
- route add -net $NET_IP gw $GATEWAY netmask $MASK $IFACE
```

bm-worker (md-1) routes in rescue:

<img width="552" alt="image" src="https://user-images.githubusercontent.com/45964815/202906749-fc7a302c-35d2-4367-8900-28d321b17045.png">

and after installimage:

<img width="591" alt="image" src="https://user-images.githubusercontent.com/45964815/202906924-b15086a4-f7e8-4581-96d8-f98749fad66f.png">

Routing on HCloud machines is not affected:

<img width="553" alt="image" src="https://user-images.githubusercontent.com/45964815/202906216-60185a4b-9ad7-4207-b669-387d38614b04.png">

**Comment by janiskemper** [comment]
We talked about it quickly. We use autosetup, cloud init, and installimage. The network configuration comes only from Hetzner through installimage. Therefore, we probably cannot do anything about it. 

Instead of doing it manually, you could also use pre kubeadm commands to automate things - just as an idea.

**Comment by Privatecoder** [comment]
had this in `preKubeadmCommands` to work around the issue however it was overwritten on the bm-workers (stayed intact on the control planes though):

```
- export IFACE=$(netstat -rn | awk '{if($4=="U")print $8}')
- export GATEWAY=$(netstat -rn | awk -v I="$IFACE" '{if($4=="UH" && $8==I)print $1}')
- export MASK=$(netstat -rn | awk -v I="$IFACE" '{if($4=="U" && $8==I)print $3}')
- export NET_IP=$(netstat -rn | awk -v I="$IFACE" '{if($4=="U" && $8==I)print $1}')
- route del -net 0.0.0.0 gw $GATEWAY netmask 0.0.0.0 $IFACE
- route del -net $NET_IP gw 0.0.0.0 netmask 255.255.255.192 $IFACE
- route add -net $NET_IP gw $GATEWAY netmask 255.255.255.192 $IFACE
```

**Comment by Privatecoder** [comment]
> We talked about it quickly. We use autosetup, cloud init, and installimage. The network configuration comes only from Hetzner through installimage. Therefore, we probably cannot do anything about it.

As routing is fine in Rescue

<img width="565" alt="image" src="https://user-images.githubusercontent.com/45964815/203016296-5f21a78d-ec5e-4f67-aa77-32baaf673ef7.png">

and very basic in installs through the Robot (thought they use installimage as well so I expected the same issue here)

<img width="590" alt="image" src="https://user-images.githubusercontent.com/45964815/203019595-2ad6e209-4e5f-4a2f-8884-ce829ce0fb43.png">

I created a ticket for Hetzner and see what they say about it.

**Comment by Privatecoder** [comment]
disabling network-config for cloud-init on bm-control-planes and bm-workers fixes the issue and should be applied with every bm-template as per Hetzners suggestion:
```
postInstallScript: |
  #!/bin/bash
  mkdir -p /etc/cloud/cloud.cfg.d && touch /etc/cloud/cloud.cfg.d/99-custom-networking.cfg
  echo "network: { config: disabled }" > /etc/cloud/cloud.cfg.d/99-custom-networking.cfg
  apt-get update && apt-get install -y cloud-init apparmor apparmor-utils
```

**Comment by batistein** [comment]
That's very interesting! Thank you very much for digging into it! Would you be able to make a PR to the [templates](https://github.com/syself/cluster-api-provider-hetzner/tree/main/templates/cluster-templates/bases)?

**Comment by Privatecoder** [comment]
sure!
