### ISSUE TITLE
CAPH-controller – secret has been modified although a provisioned machine uses it

### ISSUE THREAD

**Issue by Privatecoder** [syself/cluster-api-provider-hetzner#461]
/kind bug

**What steps did you take and what happened:**

- Create a three-node cluster with flavor `hetzner-baremetal-control-planes-remediation` / Ubuntu 20.04 HWE using a fresh kind-bootstrap-cluster.
- Moving objects to target cluster via `clusterctl move`
- all bm-nodes stay in error-state as moving the secrets seems to alter them
- the controller reports:

![image](https://user-images.githubusercontent.com/45964815/202846879-0b412016-ae54-416c-b882-6594baf2b0f6.png)

**What did you expect to happen:**

Moving the secrets from the bootstrap to the target cluster seems to alter them which should be "communicated" to the caph-controller (if so).

**Environment:**

- cluster-api-provider-hetzner version: v1.0.0-beta.7
- Kubernetes version: v1.24.8
- OS: Ubuntu 20.04 HWE

**Comment by Privatecoder** [comment]
when removing and re-adding a HetznerBareMetalHosts-object cloud-init fails with

```
[preflight] Running pre-flight checks
error execution phase preflight: couldn't validate the identity of the API Server: could not find a JWS signature in the cluster-info ConfigMap for token ID "e6lho8
```

**Comment by janiskemper** [comment]
One thing that would not work any more would be the remediation which uses the ssh key. Spontaneously I didn't come up with anything else. We will think about this and propose a solution here!

**Comment by Privatecoder** [comment]
Can't we update all bm-nodes if the secret changes, i.e. replace the existing ssh-key? This way it would (unnecessarily) get replaced once due to _moving_ but then we would not need to worry about the message anymore.

**Comment by janiskemper** [comment]
We would have to reprovision everything so that the nodes have the new ssh key. Would you say that you would expect this to happen? If the reprovisioning (which you can always trigger manually of course) happens automatically, that might occupy the cluster for a while (in situations where you might not want it)

**Comment by Privatecoder** [comment]
> Would you say that you would expect this to happen?

No and you are right – we should add to the docs, that re-provisioning is required after moving via clusterctl in order to fix the error-state.

**Comment by janiskemper** [comment]
Haha I'm not sure whether you understood correctly what I meant. I didn't mean that you expect this situation you described in the issue to happen. Obviously, that is not how it is supposed to be. 
I mean that you expect all machines to re-provision automatically if you (accidentally or not) change the secret. Independently of what happens right now when moving the cluster.

**Comment by Privatecoder** [comment]
This is what I understood. If we automatically re-provision all bm-nodes in case of a _real_ secret-change one cannot decide to re-provision the nodes step-by-step one after another when it fits best but the controller would trigger it automatically.

I did get that which is why I wrote "No" to your question if I "would expect this to happen".

To keep the logging inside the controller active – as it is right now – and to not run into the scenario above, I proposed to simply adjust the docs and cover the fact that secrets will get modified form the controller point of view after moving which happens to happen only once when setting up the cluster I guess.

**Comment by batistein** [comment]
And to add to this:
Best practice is to have a central cluster that controls multiple workload clusters. Then this problem does not occur.

**Comment by batistein** [comment]
This was more of a general advice on how to do, than with Baremetal. But even if you want to use Baremetal for the central cluster, you could start with hcloud, do the move, and then add Baremetal nodes and switch over. But of course that is almost the same as re-provisioning.

**Comment by janiskemper** [comment]
So to sum up: There is this one use case where the current strategy of throwing an error because of a secret change does not really make sense. We will look into how this can be approached best and give our suggestions here.

**Comment by janiskemper** [comment]
Sorry, I didn't mean to play this down in any way, if you had the impression! I was referring to the fact that this error that you get when moving the cluster is a valid one in all cases BUT the one where you move the cluster. 

And yes, you can still work around this by having a HCloud management cluster and to never move this one, or to add the bare metal machines only after moving it, as @batistein pointed out. 

However, we still want to solve this issue! That's what we will think about.

**Comment by Privatecoder** [comment]
No worries, I was just trying to point out that this is exactly what happens when following the quick-start guide with any of the two mentioned templates.

> or to add the bare metal machines only after moving it, as @batistein pointed out.

Just in theory: How would that work? Afaik I have to decide if control-planes are bm or hcloud. So if I opt for bm I cannot _"add the bare metal machines only after moving it"_ as they're the control-planes.

The only option I see here is to create a single-replica bm-control-plane cluster, scale it up to three after moving and then re-provisioning the first one which is probably about the same as to just start with three initially and re-provision them one by one afterwards.

**Comment by Privatecoder** [comment]
btw. thanks for your support and great tool @batistein & @janiskemper! 👍

**Comment by janiskemper** [comment]
Yes, looking at the control planes it's true, that it is the same as reprovisioning, like you and (@batistein) said.
That works at least (if you wanna do that only once), but for doing it more often, e.g. for testing, that is a bit stupid and we'll find a better solution!

I really appreciate your message btw ;)

**Comment by Privatecoder** [comment]
Not exactly related but the _placement group_ for hcloud-control-planes should not be created if any of the bm-control-planes-templates is being used – just cosmetics ;)

**Comment by Privatecoder** [comment]
@batistein what is the proper / quickest way to re-provision a bm-node?

Currently I remove the `HetznerBareMetalHost`, `HetznerBareMetalMachine` and `KubeadmConfig` and then re-add the `HetznerBareMetalHost`.

**Comment by batistein** [comment]
> Currently I remove the HetznerBareMetalHost, HetznerBareMetalMachine and KubeadmConfig and then re-add the HetznerBareMetalHost.

You only need to remove the Machine object. All the other objects you mentioned are referenced by the machine object in a direct or indirect way.

**Comment by Privatecoder** [comment]
I saw the references, however I found that removing the Machine object did not work last time I checked as the kubeadm-join-token in the referenced `KubeadmConfig` expired (which it does after 23 hours I think) so I removed that as well and ended up removing everything.

How can I properly trigger a `kubeadm token create` for the `KubeadmConfig` to be updated?

**Comment by janiskemper** [comment]
Proposed solution: Remove the line from the code [here](https://github.com/syself/cluster-api-provider-hetzner/blob/main/api/v1beta1/hetznerbaremetalhost_types.go#L306), where we compare the secret's current resource version with the previous one. If it changed, we assume the secret changed. When moving the cluster the resource version updates, even though nothing in the secret's data changed. Therefore, we want to replace the comparison of resource versions by checking only if the data itself changed. 

I'm not 100% sure if there are some edge cases that will bring the operator into trouble where the secret actually changes without changing the data. However, I think that the use case of moving the bare metal cluster is very relevant, so I would still go ahead!

I can also make a PR for this!

**Comment by batistein** [comment]
This is exactly what we will do now ;) Using resourceVersion is a more [native approach](https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes) for kubernetes by using etcd watch api which is generating these.

**Comment by janiskemper** [comment]
@Privatecoder, we just released the new version. Please give us your feedback if it works for you as expected!
