### ISSUE TITLE
Failed with two control plane nodes

### ISSUE THREAD

**Issue by mxzinke** [syself/cluster-api-provider-hetzner#472]
/kind bug

On trying to create a cluster, it failed with two control plane nodes.

**What steps did you take and what happened:**

```sh
$ clusterctl generate cluster test-cluster-12 > test-cluster-12.yaml
$ kubectl apply -f test-cluster-12.yaml
kubeadmconfigtemplate.bootstrap.cluster.x-k8s.io/test-cluster-12-md-0 created
cluster.cluster.x-k8s.io/test-cluster-12 created
machinedeployment.cluster.x-k8s.io/test-cluster-12-md-0 created
machinehealthcheck.cluster.x-k8s.io/test-cluster-12-control-plane-unhealthy-5m created
machinehealthcheck.cluster.x-k8s.io/test-cluster-12-md-0-unhealthy-5m created
hcloudmachinetemplate.infrastructure.cluster.x-k8s.io/test-cluster-12-control-plane created
hcloudmachinetemplate.infrastructure.cluster.x-k8s.io/test-cluster-12-md-0 created
hetznercluster.infrastructure.cluster.x-k8s.io/test-cluster-12 created
The KubeadmControlPlane "test-cluster-12-control-plane" is invalid: spec.replicas: Forbidden: cannot be an even number when etcd is stacked
```

After changing the replicas to 3, the cluster got up & running with **just one node**!

**What did you expect to happen:**
I would expect that the cluster generating command gives me the creates a cluster with two control plane nodes.

**Environment:**
```sh
export CONTROL_PLANE_MACHINE_COUNT=2
export WORKER_MACHINE_COUNT=5
```

- cluster-api-provider-hetzner version: v1.0.0-beta.8
- Kubernetes version: 1.25.3 on Minikube (Hyperkit)

**Comment by janiskemper** [comment]
Hi @mxzinke! 
Thanks for trying out CAPH! 

As etcd uses the Raft algorithm, it cannot deal with an even number of nodes because they don't add anything to the stability of the cluster. Therefore, two control planes are useless. You should go to either one or three, depending on your use case. 

Did you install the CCM and CNI as the first control plane came up? Otherwise, the next two control planes won't come up!

**Comment by mxzinke** [comment]
Hi @janiskemper!

Thanks for the explanation, I didn't though of etcd not being compatible because of Raft... Okay, then it's basically done.

My CNI was not working correctly, now it's working fine. Nice work @ all contributors & maintainers!
