### ISSUE TITLE
Kubelet failed to boot up

### ISSUE THREAD

**Issue by Stringls** [syself/cluster-api-provider-hetzner#553]
/gke bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I deploy a workload cluster in Hetzner via Cluster API on GKE cluster.
It starts to deploy the contol-plane and stuck on `KubeadmInit`. I tried to debug it and found these logs

```
Unfortunately, an error has occurred:
        timed out waiting for the condition

This error is likely caused by:
        - The kubelet is not running
        - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
```

kubelet logs say this
```
Jan 25 20:59:14 sys-cluster-control-plane-59n6g kubelet[3062]: E0125 20:59:14.891103    3062 kubelet.go:2448] "Error getting node" err="node \"sys-cluster-control-plane-59n6g\" not found"
Jan 25 20:59:14 sys-cluster-control-plane-59n6g kubelet[3062]: E0125 20:59:14.991749    3062 kubelet.go:2448] "Error getting node" err="node \"sys-cluster-control-plane-59n6g\" not found"
Jan 25 20:59:15 sys-cluster-control-plane-59n6g kubelet[3062]: E0125 20:59:15.092887    3062 kubelet.go:2448] "Error getting node" err="node \"sys-cluster-control-plane-59n6g\" not found"
Jan 25 20:59:15 sys-cluster-control-plane-59n6g kubelet[3062]: E0125 20:59:15.193451    3062 kubelet.go:2448] "Error getting node" err="node \"sys-cluster-control-plane-59n6g\" not found"
Jan 25 20:59:15 sys-cluster-control-plane-59n6g kubelet[3062]: E0125 20:59:15.294066    3062 kubelet.go:2448] "Error getting node" err="node \"sys-cluster-control-plane-59n6g\" not found"
Jan 25 20:59:15 sys-cluster-control-plane-59n6g kubelet[3062]: I0125 20:59:15.317520    3062 kubelet_node_status.go:70] "Attempting to register node" node="sys-cluster-control-plane-59n6g"
Jan 25 20:59:15 sys-cluster-control-plane-59n6g kubelet[3062]: E0125 20:59:15.319603    3062 kubelet_node_status.go:92] "Unable to register node with API server" err="Post \"https://142....15:443/api/v1/nodes\": EOF" nod>
Jan 25 20:59:15 sys-cluster-control-plane-59n6g kubelet[3062]: E0125 20:59:15.395179    3062 kubelet.go:2448] "Error getting node" err="node \"sys-cluster-control-plane-59n6g\" not found"
Jan 25 20:59:15 sys-cluster-control-plane-59n6g kubelet[3062]: E0125 20:59:15.496277    3062 kubelet.go:2448] "Error getting node" err="node \"sys-cluster-control-plane-59n6g\" not found"
Jan 25 20:59:15 sys-cluster-control-plane-59n6g kubelet[3062]: E0125 20:59:15.597285    3062 kubelet.go:2448] "Error getting node" err="node \"sys-cluster-control-plane-59n6g\" not found"
Jan 25 20:59:15 sys-cluster-control-plane-59n6g kubelet[3062]: E0125 20:59:15.698296    3062 kubelet.go:2448] "Error getting node" err="node \"sys-cluster-control-plane-59n6g\" not found"
Jan 25 20:59:15 sys-cluster-control-plane-59n6g kubelet[3062]: E0125 20:59:15.707752    3062 controller.go:144] failed to ensure lease exists, will retry in 7s, error: Get "https://142....15:443/apis/coordination.k8s.io/>
```

**What did you expect to happen:**

I expect the cluster to be deployed successfully.
Control-plane get passed `KubeadmInit` stage

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

It happens sometimes and sometimes all good. And I don't get the reason why it's happening

**Environment**

- cluster-api-provider-hetzner version: latest
- Kubernetes version: (use `kubectl version`) 1.25.2 on Hetzner VMs and 1.25.3 on GKE cluster
- OS (e.g. from `/etc/os-release`): I have a cluster on GKE as a management cluster and `ubuntu-22.04` on Hetzner VMs

**Comment by Stringls** [comment]
I haven't solved the issue yet. Please, help me :)
If you need more logs, just ping me, I would be happy to share it with you

**Comment by janiskemper** [comment]
Did you install the CCM?

**Comment by Stringls** [comment]
Am I supposed to do it before Kubernetes cluster initialization. Cause I have only control plane and Kubernetes initialization failed due to unregistered node, in #cluster-api slack channel said it's the problem with a network layer, but I do not know how to debug it

**Comment by Stringls** [comment]
lol, it's deployed right now. It's so unstable that I cannot even tell what's the root of the cause

**Comment by Stringls** [comment]
> lol, it's deployed right now. It's so unstable that I cannot even tell what's the root of the cause

It's deployed 2 times in a row and I honestly do not understand the reason of earlier failures. Could it be the problem from Hetzner side? I use the same template as `clusterctl generate cluster`, I do not change anything, but from time to time it works and sometimes it fails. Recently, this problem happens more often, so I am wondering, perhaps it's an issue from Hetzner side?

**Comment by Stringls** [comment]
Still no updates on it. So I'll close it for now
