### ISSUE TITLE
GHA Workflows using SYSELF_APP_PRIVATE_KEY fail in forks

### ISSUE THREAD

**Issue by apricote** [syself/cluster-api-provider-hetzner#554]
/kind bug

**What steps did you take and what happened:**

I forked this repository to create pull requests (#551 #552). The workflow `Labels` failed in those PRs. Additionally, I get emails every 30 minutes from GitHub, that the workflow `Renovate` failed in my fork. Both fail at the same step:

```
2023-01-25T11:28:58.5203952Z ##[group]Run tibdex/github-app-token@v1
2023-01-25T11:28:58.5204230Z with:
2023-01-25T11:28:58.5204604Z   github_api_url: https://api.github.com
2023-01-25T11:28:58.5204991Z   repository: syself/cluster-api-provider-hetzner
2023-01-25T11:28:58.5205357Z ##[endgroup]
2023-01-25T11:28:58.6318613Z ##[error]Error: Input required and not supplied: app_id
```

**What did you expect to happen:**

I expected the CI pipeline for forks to run successfully, and to not receive notifications and emails every 30 minutes about a failed scheduled pipeline.

**Anything else you would like to add:**

The steps use secrets that are not available in my fork.

```
      - name: Generate Token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.SYSELF_APP_ID }}
          private_key: ${{ secrets.SYSELF_APP_PRIVATE_KEY }}
```

**Environment:**

Fork is at e957613d15cdd7754f988efc119a27b17f47dceb

**Comment by batistein** [comment]
The issue is because of this issue: https://github.com/tibdex/github-app-token/issues/25
maybe we need to find another way to enable forks.

**Comment by batistein** [comment]
@apricote is this still happening? I changed the workflow a little bit and we are now using pull_request_target in gha.

**Comment by apricote** [comment]
I don't have an open PR, but I think your changes should have fixed that.

There are still scheduled workflows running that fail: https://github.com/syself/cluster-api-provider-hetzner/blob/f4d246c80be859e6d038eedcbdf6b744cef84e2b/.github/workflows/schedule-link-checker.yml#L4-L5

This [could be fixed](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution#example-only-run-job-for-specific-repository) by restricting the scheduled jobs to `if: github.repository == 'syself/cluster-api-provider-hetzner'` or perhaps `if: vars.RUN_SCHEDULED_JOBS == 'true'` to still allow testing/running scheduled jobs in forks if explicitly opted in by setting the variable
