### ISSUE TITLE
Unable to update controlplane by editing KubeadmControlPlane

### ISSUE THREAD

**Issue by jabbrwcky** [syself/cluster-api-provider-hetzner#591]
/kind bug

**What steps did you take and what happened:**

I deployed a k8s cluster with flavor `hcloud-network` with k8s version 1.24.10

After it finished I updated the KubernetesVersion to 1.25.6 to test the rolling upgrade of the controlplane.
The provider did perform a rolling upgrade but the controlplane still reports v1.24.10 after the upgrade

**What did you expect to happen:**

I expected the controlplane to be updated to the next kubernetes version

**Anything else you would like to add:**

I suspect that the issue is here: https://github.com/syself/cluster-api-provider-hetzner/blob/main/templates/cluster-templates/bases/hcloud-kcp-ubuntu.yaml#L191

The `${KUBERNETES_VERSION}` is expanded when the cluster-api generates the template, effectively freezing the version to the one initially specified:

```yaml
preKubeadmCommands:
      - export CRUN=1.7.2
      - export CONTAINERD=1.6.8
      - export KUBERNETES_VERSION=$(echo 1.24.10 | sed 's/^v//')
```

I think it should be escaped so the variable is only evaluated at script execution time like this:

```yaml
preKubeadmCommands:
      - export CRUN=1.7.2
      - export CONTAINERD=1.6.8
      - export KUBERNETES_VERSION=$(echo ${KUBERNETES_VERSION} | sed 's/^v//')
```

Both `KubeadmConfigTemplate` and `KubeadmControlPlane` contain the same script so I am not sure where the main fault lies.

**Environment:**

- cluster-api-provider-hetzner version: v1.0.0-beta.14
- Kubernetes version: (use `kubectl version`)
- OS (e.g. from `/etc/os-release`):

**Comment by batistein** [comment]
Hi, thanks for trying it out and reporting back.

The flavors that come with the release are not meant for updating as such. What you tried would normally be done a little differently. 
See: https://cluster-api.sigs.k8s.io/tasks/upgrading-clusters.html#how-to-upgrade-the-kubernetes-control-plane-version

We use the ENV variable for testing kubernetes update in our automatic tests (e2e). I add here the links to it if there is interest:

- https://github.com/syself/cluster-api-provider-hetzner/blob/main/.github/workflows/e2e-upgrade-kubernetes.yaml
- https://github.com/syself/cluster-api-provider-hetzner/blob/main/test/e2e/upgrade_kubernetes_test.go

**Comment by batistein** [comment]
In general, the cluster api only ensures that the lifecycle is implemented. Especially with topics like kubernetes update, the node must also be prepared. In most cases, in production you would not only update the kubernetes version as you would also update other necessary things like container runtime etc.. With caph there are two options to do this: 
1. by using a custom image through packer 
2. by customizing the cmd commands of cloud-init (see pre and postkubeadm commands)

to update the k8s version for example in variant 1 (which is usually used in production) you would first build a new node image using packer and then create a new HcloudMachineTemplate which references the snapshot. After that you only need to adjust the reference of the HcloudMachineTemplate and the Kubernetes version in the KubeadmControlPlane and in the MachineDeployment. The Kubernetes version in the spec of the objects is relevant for generating the cloud-init data e.g with kubeadm, all other dependencies such as kubeadm itself should have been provided in the correct version in the nodeimage beforehand.

**Comment by jabbrwcky** [comment]
That makes perfect sense. Thank you for the detailed explanation. I may have been spoiled by first setting up an EKS cluster with managed nodegroups via cluster-admin and testing the version upgrader there, before trying to update the HCloud cluster.

But in the end the main difference is that AWS already provides configured images 😅
