### ISSUE TITLE
Provide Logs for unit-tests, too

### ISSUE THREAD

**Issue by guettli** [syself/cluster-api-provider-hetzner#737]
/kind feature

The github web-gui is limited, if the logs of failing unit-tests are long.

Example:
https://github.com/syself/cluster-api-provider-hetzner/actions/runs/4561797363/jobs/8048174090

**Describe the solution you'd like**

It would be great if you could provide the logs as artifacts, similar to the e2e-tests.

**Comment by batistein** [comment]
@guettli still relevant?

**Comment by guettli** [comment]
Still relevant, but at the moment not important. I close it.
