### ISSUE TITLE
HCloudMachineTemplate finaliser blocking deletion

### ISSUE THREAD

**Issue by simonostendorf** [syself/cluster-api-provider-hetzner#832]
/kind bug

**What steps did you take and what happened:**
I deleted all my clusters (they are build from ClusterClasses). The HCloudMachineTemplates that were created by the cluster stay there. If I want to manually delete them they don't get deleted. I have to remove the finaliser to remove them from the cluster.

**What did you expect to happen:**
Deleting the HCloudMachineTemplate should work because there are no machines that exist from the template.

**Anything else you would like to add:**
(nothing)

**Environment:**

- cluster-api-provider-hetzner version: v1.0.0-beta.17
- Kubernetes version: (use `kubectl version`) v1.27.3
- OS (e.g. from `/etc/os-release`): debian-11

**Comment by aniruddha2000** [comment]
Yes, we are working on it to remove the finalizer present in https://github.com/syself/cluster-api-provider-hetzner/blob/main/controllers/hcloudmachinetemplate_controller.go#L128

**Comment by souhardya79** [comment]
Working on it to solve the bug

**Comment by simonostendorf** [comment]
> Working on it to solve the bug

Hello, what is the current status here?
