### ISSUE TITLE
Add linting to CI checks

### ISSUE THREAD

**Issue by janiskemper** [syself/cluster-api-provider-hetzner#838]
/kind bug

**What steps did you take and what happened:**
The current CI does not include checks for Go linting. Locally `make lint` gives errors that the CI does not check for. 

**What did you expect to happen:**
I expect to have the same or at least similar behaviour in the CI as I have locally when running `make verify` and `make lint`.

**Comment by kranurag7** [comment]
@janiskemper I checked the workflows and ran the tests locally. As per #839, we should also include tests for golang-ci lint in a separate workflow, this was missing as of now and that was the reason for diversion in the results locally and in CI. I will create a workflow to cover that.

**Comment by janiskemper** [comment]
thanks @kranurag7, sounds good! I had to fix one issue that caused the E2E test to fail in this PR https://github.com/syself/cluster-api-provider-hetzner/pull/839 but am done now. As soon as this PR is merged, there shouldn't be anything that blocks your work!

**Comment by batistein** [comment]
@kranurag7 the workflow is already there: https://github.com/syself/cluster-api-provider-hetzner/blob/main/.github/workflows/pr-lint.yml 
But somehow it's not triggered see: https://github.com/syself/cluster-api-provider-hetzner/actions/workflows/pr-lint.yml
