### ISSUE TITLE
clusterctl fails with cert-manager installation when moving from bootstrap to management cluster

### ISSUE THREAD

**Issue by rochecompaan** [syself/cluster-api-provider-hetzner#864]
/kind bug

**What steps did you take and what happened:**

I followed the steps in the quickstart up to the step where one moves cluster-api objects to the control plane cluster. I chose the hetzner-baremetal-control-planes flavor with 3 control plane nodes and left the worker count at the default of 0.

It failed with this bug (Certmanager pods not starting because of untolerated taint control-plane #7074) previously reported on the cluster-api issue tracker: https://github.com/kubernetes-sigs/cluster-api/issues/7074

**What did you expect to happen:**

I expected to move the cluster-api objects to the control plane.

**Anything else you would like to add:**

This is either a bug, or the documentation needs to be updated to clarify whether one can transfer cluster-api objects to the control plane or if one needs to keep the cluster-api objects in a management cluster.

**Environment:**

- cluster-api-provider-hetzner version: v1.0.0-beta.18 (I'm assuming the latest, how do I check?)
- Kubernetes version: v1.27.2
- OS (e.g. from `/etc/os-release`): Arch Linux

**Comment by batistein** [comment]
The installation of cert-manager and cluster-api components like core, bootstrap, control-plane is handled by the cluster-api/clusterctl project. So it's not a bug of this provider.

It's usually not recommended to start the controllers on the control-plane itself. You would need to patch the toleration. I'm not sure if this is supported by clusterctl. If you were using the cluster-api operator, you could patch the resource in the appropriate custom resource object. That way it should be possible to start the cluster-api stack on a control plane as well.

**Comment by rochecompaan** [comment]
It would be helpful if the documentation can be explicit about which configurations or flavors apply to the section "Moving components" in the quick start and not assume that it will work for all configurations.
