### ISSUE TITLE
failed to handle incomplete boot - installImage: unexpected hostname

### ISSUE THREAD

**Issue by rochecompaan** [syself/cluster-api-provider-hetzner#868]
/kind bug

**What steps did you take and what happened:**

I followed the steps in the quickstart to provision a cluster with a hcloud control plane and a bare metal machines for the workload cluster.

I have repeated these steps at least four times, and every time it has taken at least 2 hours or more to provision the whole cluster. I see the following error repeatedly:

```
failed to reconcile HetznerBareMetalHost default/bm-0: action \"provisioning\" failed: failed to handle incomplete boot - installImage: unexpected hostname: bm-intellovations-md-1-zdw4w
```

Eventually, the error above is handled, and a host is provisioned.

Complete caph controller log attached. 
[logs.zip](https://github.com/syself/cluster-api-provider-hetzner/files/12323398/logs.zip)

**What did you expect to happen:**

Provisioning servers within 30 minutes or less without repeating errors.

**Environment:**

- cluster-api-provider-hetzner version: v1.0.0-beta.18
- Kubernetes version: v1.27.4
- OS (e.g. from `/etc/os-release`): Arch Linux

**Comment by batistein** [comment]
The problem lays in the provisioning of the machine. Please check: `/var/lib/cloud/instance/scripts/runcmd`
It looks like there is a problem with containerd

**Comment by janiskemper** [comment]
we were able to reproduce it temporarily and it's related to installimage, not cloud-init. However, as we were at the point of debugging it with all the output we can get from installimage, we weren't able to reproduce it anymore.

This is probably some issue with installimage which should be fixed if you try it again.

**Comment by rochecompaan** [comment]
Thanks for reporting back. I have lost the opportunity to retest this since we had to go for a different deployment solution. I'll revisit this in the future when I have the opportunity.
