### ISSUE TITLE
v1.0.0-beta.21 has no build artifacts

### ISSUE THREAD

**Issue by cyclingwithelephants** [syself/cluster-api-provider-hetzner#890]
/kind bug

**What steps did you take and what happened:**
It seems the latest release ([v1.0.0-beta.21](https://github.com/syself/cluster-api-provider-hetzner/releases/tag/v1.0.0-beta.21)) has no artifacts to downloads, failing e.g. `clusterctl init` calls

**What did you expect to happen:**
clusterctl would be able to download the [v1.0.0-beta.21](https://github.com/syself/cluster-api-provider-hetzner/releases/tag/v1.0.0-beta.21) artifacts

**Comment by batistein** [comment]
@cyclingwithelephants it was not published at the time of your question. I just released it now.

**Comment by cyclingwithelephants** [comment]
@batistein For a few hours the release existed but had no artifacts attached to it, not sure if the reason for that is on your end or githubs. Not sure if it's something worth looking into. Unfortunately it didn't occur to me to take a screenshot to share

As you note it's fixed now. Thanks!
