### ISSUE TITLE
Cannot connect to control plane on IPv6 when IPv4 is disabled.

### ISSUE THREAD

**Issue by BlakeB415** [syself/cluster-api-provider-hetzner#899]
/kind bug

**What steps did you take and what happened:**
Create a cluster with ``enableIPv4`` ``false`` and ``enableIPv6`` to ``true``.
Results in WaitingForNodeRef on those machines.

**What did you expect to happen:**
The nodes to join the cluster.

**Anything else you would like to add:**
It seems to be using the IPv4 address of the LB (which can't be disabled), instead of the IPv6 one. The machines don't have IPv4 access.

I believe it should only use the LB IPv4 when enableIPv4 is set to true. If enableIPv4 is explicitly false and enableIPv6 is true, it should use the IPv6 address of the LB.

**Environment:**

- cluster-api-provider-hetzner version: v1.0.0-beta.22
- Kubernetes version: (use `kubectl version`) v1.25.5
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04.1 LTS

**Comment by BlakeB415** [comment]
I looked through the code and it seems that this would have to be an option on the HetznerCluster object as that's what controls the API server endpoint URI.

**Comment by batistein** [comment]
The controlPlaneEndpoint doesn't come from us it's imported. But in general you can solve this problem by using a domain for the `controlPlaneEndpoint.host`

**Comment by BlakeB415** [comment]
> The controlPlaneEndpoint doesn't come from us it's imported. But in general you can solve this problem by using a domain for the `controlPlaneEndpoint.host`

Alright, that would work. 

I also have another issue where when the Hetzner private network is disabled, it forces IPv4 on. This isn't required anymore as the LB supports IPv6.

**Comment by BlakeB415** [comment]
> The controlPlaneEndpoint doesn't come from us it's imported. But in general you can solve this problem by using a domain for the `controlPlaneEndpoint.host`

Alright, that would work. 

I just tested it and the LB doesn't support IPv6 targets for some reason. So I guess using a private network is the only option. That's unfortunate.
