### ISSUE TITLE
Follow phase of Machine in HetznerBareMetalMachine object

### ISSUE THREAD

**Issue by janiskemper** [syself/cluster-api-provider-hetzner#941]
## Description

We should have a phase in the status of the HetznerBareMetalMachine object which is optional and omitempty. This phase should be similar to the phases a clusterv1.Machine object goes through and should depend on the host object's provisioningState. 

We should also update the printcolumns accordingly

**Comment by aniruddha2000** [comment]
what is a host object in this case?

**Comment by janiskemper** [comment]
HetznerBareMetalHost
