### ISSUE TITLE
Test whether conditions are set

### ISSUE THREAD

**Issue by janiskemper** [syself/cluster-api-provider-hetzner#943]
## Tasks:
- [x] Test https://github.com/syself/cluster-api-provider-hetzner/pull/942
- [ ] Search for other conditions and see whether they are being tested or not. Make a list and post it as comment to this issue
- [ ] Implement tests

**Comment by janiskemper** [comment]
I believe that we have not thought about which other conditions we might not have tested. I re-open until that list is done!

**Comment by aniruddha2000** [comment]
list of places conditions to be tested - 

- https://github.com/syself/cluster-api-provider-hetzner/blob/cb8f7451aa8f4a87d90d11ef9733612767871ef0/pkg/services/hcloud/server/server.go#L382
- https://github.com/syself/cluster-api-provider-hetzner/blob/cb8f7451aa8f4a87d90d11ef9733612767871ef0/pkg/services/hcloud/server/server.go#L449
- https://github.com/syself/cluster-api-provider-hetzner/blob/cb8f7451aa8f4a87d90d11ef9733612767871ef0/pkg/services/hcloud/server/server.go#L489
- https://github.com/syself/cluster-api-provider-hetzner/blob/cb8f7451aa8f4a87d90d11ef9733612767871ef0/pkg/services/hcloud/server/server.go#L546
- https://github.com/syself/cluster-api-provider-hetzner/blob/cb8f7451aa8f4a87d90d11ef9733612767871ef0/pkg/services/hcloud/server/server.go#L569
- https://github.com/syself/cluster-api-provider-hetzner/blob/cb8f7451aa8f4a87d90d11ef9733612767871ef0/pkg/services/hcloud/server/server.go#L136
- https://github.com/syself/cluster-api-provider-hetzner/blob/cb8f7451aa8f4a87d90d11ef9733612767871ef0/pkg/services/hcloud/server/server.go#L154
- https://github.com/syself/cluster-api-provider-hetzner/blob/cb8f7451aa8f4a87d90d11ef9733612767871ef0/pkg/services/hcloud/server/server.go#L174

**Comment by aniruddha2000** [comment]
https://github.com/syself/cluster-api-provider-hetzner/pull/1010 is in progress and i was fixing the mocks IIRC

**Comment by batistein** [comment]
@aniruddha2000 what is the status here?

**Comment by janiskemper** [comment]
@aniruddha2000 ?

**Comment by aniruddha2000** [comment]
@janiskemper @batistein Ahh sorry I missed that, I need some time to focus on #1010 as that PR is quite big and I have to recap what I did as well

**Comment by guettli** [comment]
@janiskemper I am unsure if it makes sense to keep this issue open. There are many parts which are not covered by envTests yet. Maybe the first step would be to generate a coverage report, so that we know which percentage is covered by tests. Janis, what do you think: Should we keep this issue open?

**Comment by janiskemper** [comment]
we can still find it even if it is closed. I am not sure if we implemented all these tests mentioned here.
